### ISSUE TITLE
DVD playback always crashes, regardless of DVD

### ISSUE THREAD

**Issue by mattreecebentley** [xbmc/xbmc#14748]
### Describe the bug
DVD's will play if you select the ifo file through the files menu, but quickly crash kodi.

## Expected Behavior
Should play without crashing.

## Actual Behavior
It crashes.

### To Reproduce

1. Select files from video menu
2. Navigate to the DVD's video_ts folder
3. Select the video_ts.ifo

### Debuglog
The debuglog can be found here:
https://paste.kodi.tv/oxudebipew.kodi
https://paste.kodi.tv/ebizohajal.kodi

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
The bug has been present ever since I started using Kodi.

No other media player I own crashes during DVD playback on this machine.
The machine is stable.

### Your Environment
Used Operating system:
Windows 10 1803 x64

 - Kodi versions:
18 alpha KodiSetup-20180918-fea8a299-master-x64
KodiSetup-20181030-abaf6171-master-x64
kodi-18.0-Leia_alpha2-x64
KodiSetup-20180603-dba439f5-master-x64

**Comment by Rechi** [comment]
@mattreecebentley retry with https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20181031-d35df9ca-depends-dvdcss-x64.exe and report back.
For me it fixed a non starting Kodi, if an iso was mounted.

**Comment by mattreecebentley** [comment]
> 
> 
> @mattreecebentley retry with https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20181031-d35df9ca-depends-dvdcss-x64.exe and report back.
> For me it fixed a non starting Kodi, if an iso was mounted.

That's not the same issue, please read the bug report.

**Comment by Rechi** [comment]
I've read it and I know you described something different, but this is what happened on my system and your crash could have caused by the same code.
Please attach the dmp file (like @Agrv did) so I can stop guessing.

**Comment by mattreecebentley** [comment]
Or you could just, you know, play a DVD.
Anyway, debuglog attached for your version.

[Kodi.zip](https://github.com/xbmc/xbmc/files/2536542/Kodi.zip)

**Comment by Rechi** [comment]
I already tried playing back a DVD, but here it doesn't crash Kodi (maybe because I can only try with ISOs, no DVD drive in my dev machine).

Your crash dump already gave some info, resubmit a new one using https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20181101-9b67799c-windows-ffmpeg-x64.exe. This version includes debug symbols for FFmpeg. Your crash happened somewhere in one of their libraries.

**Comment by Agrv** [comment]
Hi, I still don't know if I have the same problem, could you please advise if I should open a new bug report? In any case, here is the log and crashlog with the ffmpeg version.
[kodi_ffmpeg_log_and_crashlog.zip](https://github.com/xbmc/xbmc/files/2545715/kodi_ffmpeg_log_and_crashlog.zip)

**Comment by Rechi** [comment]
@Agrv I don't know if you crash is different as @mattreecebentley hasn't provided a new crash dump yet.
Please retry with Render method set to Software (https://kodi.wiki/view/Settings/Player/Videos#Render_method) and report back.

@afedchin it crashes at https://github.com/xbmc/FFmpeg/blob/4.0.3-Leia-Beta5/libavcodec/dxva2.c#L776 with `surface == nullptr`, do you have any idea what could go wrong?

**Comment by mattreecebentley** [comment]
[Kodi.zip](https://github.com/xbmc/xbmc/files/2591425/Kodi.zip)

Done.
FWIW, doesnt crash on all DVD's like I thought - the one it's crashing on above is Watership Down - whereas on Duckman and The Great Gatsby seems to be fine.
Also failed on DVD of the Dark Crystal, as far as I recall.

**Comment by Rechi** [comment]
The crashes happen at the same place so it looks like it's the same bug.

@mattreecebentley did software rendering fix the crashes? I know it's not a proper fix, just want to be sure it's only hw rendering which causes issues.

**Comment by mattreecebentley** [comment]
I don't have those DVD's on hand at the moment to check, but it seems extremely unlikely to me.
Everything else plays fine through hardware rendering, so there's no real logic there for only Some DVD's failing with it

**Comment by Agrv** [comment]
The crash still happens in software rendering mode, and in Kodi 18.0 RC1. Kodi log, crashlog and stacktrace files attached. Just like @mattreecebentley said, it does not happen on all DVD ISOs.
[kodi18rc1-dvd-crashlog.zip](https://github.com/xbmc/xbmc/files/2635970/kodi18rc1-dvd-crashlog.zip)

**Comment by pkerling** [comment]
Can you test on any other platform (preferably not UWP) to verify whether it is a Windows-only issue?

**Comment by Agrv** [comment]
It appears to be a Windows-only issue: tested on Linux (Ubuntu 18.10 with Kodi 18.0 RC3) and the issue is not present. On Windows 10, same Kodi version and same hardware, some DVD ISOs crash Kodi a few seconds after launching the playback, but before actually starting the playback.

**Comment by pkerling** [comment]
OK then unfortunately I cannot help you personally and will join you in hoping that a Windows dev steps up to investigate

**Comment by afedchin** [comment]
> @Agrv I don't know if you crash is different as @mattreecebentley hasn't provided a new crash dump yet.
> Please retry with Render method set to Software ([kodi.wiki/view/Settings/Player/Videos#Render_method](https://kodi.wiki/view/Settings/Player/Videos#Render_method)) and report back.
> 
> @afedchin it crashes at [xbmc/FFmpeg:libavcodec/dxva2.c@`4.0.3-Leia-Beta5`#L776](https://github.com/xbmc/FFmpeg/blob/4.0.3-Leia-Beta5/libavcodec/dxva2.c#L776) with `surface == nullptr`, do you have any idea what could go wrong?

I have no idea why ffmpeg cant find a surface. Kodi writes error message into the log if there is no more free surfaces in pool. I didn't find the message in the provided logs, so it meant that Kodi provides surfaces to ffmpeg lib.

I wasn't able to reproduce the issue

**Comment by afedchin** [comment]
It looks like a bug in ffmpeg. Not all mpeg2 files are affected but only those which start with non I-Frame because ffmpeg tries to get an index of previous frame but there is no previous picture. 
I'll try to patch ffmpeg to avoid this crash, but it will hide the issue.

@FernetMenta have you any idea?

**Comment by fritsch** [comment]
Not sure how that happens, we have: 88d75f465bbb6ef55cc269ce929bd65cbc32a019 in place still to only initiate dxva when we get an iframe.

**Comment by fritsch** [comment]
To answer my own question: Workaround is h264 only.

**Comment by afedchin** [comment]
this patch fixes the issue

```patch
--- a/libavcodec/dxva2_mpeg2.c
+++ b/libavcodec/dxva2_mpeg2.c
@@ -48,11 +48,11 @@ static void fill_picture_parameters(AVCodecContext *avctx,
     memset(pp, 0, sizeof(*pp));
     pp->wDecodedPictureIndex         = ff_dxva2_get_surface_index(avctx, ctx, current_picture->f);
     pp->wDeblockedPictureIndex       = 0;
-    if (s->pict_type != AV_PICTURE_TYPE_I)
+    if (s->pict_type != AV_PICTURE_TYPE_I && s->last_picture_ptr)
         pp->wForwardRefPictureIndex  = ff_dxva2_get_surface_index(avctx, ctx, s->last_picture.f);
     else
         pp->wForwardRefPictureIndex  = 0xffff;
-    if (s->pict_type == AV_PICTURE_TYPE_B)
+    if (s->pict_type == AV_PICTURE_TYPE_B && s->next_picture_ptr)
         pp->wBackwardRefPictureIndex = ff_dxva2_get_surface_index(avctx, ctx, s->next_picture.f);
     else
         pp->wBackwardRefPictureIndex = 0xffff;
```

**Comment by FernetMenta** [comment]
looks reasonable to me. why is this need now and not on earlier versions?

**Comment by FernetMenta** [comment]
@afedchin good catch. are you going to submit your patch upstream?

**Comment by afedchin** [comment]
@FernetMenta please sent the patch on behalf of yourself if you have a time

**Comment by FernetMenta** [comment]
> if you have a time

that's not the case and their antiquated mailing list does not speed up things. maybe just mention the bug and your fix on their irc channel

**Comment by afedchin** [comment]
I've sent the patch but it awaits moderator approval of ffmepg-devel

**Comment by Voyager1** [comment]
@afedchin in the meantime, you could perhaps put a patch in /xbmc/tools/buildsteps/windows so that we get a fixed build?

**Comment by afedchin** [comment]
@Voyager1 yes, I know. I just wanna be sure that the patch is right.

looks like I did something wrong with ffmpeg-devel. I don't see my patch in mailing list. @FernetMenta can you help?

**Comment by MartijnKaijser** [comment]
@voyager1 ffmpeg patches need to be put on top of our fork and tagged if we want to do that

**Comment by Voyager1** [comment]
@MartijnKaijser - agree. Note that there are three patches for ffmpeg already in the folder I mentioned.

**Comment by afedchin** [comment]
@Voyager1 these patches for build system not for ffmpeg itself.

**Comment by Voyager1** [comment]
all is good then :-)

**Comment by FernetMenta** [comment]
@afedchin can you forward me the mail you sent to ffmpeg-devel?

**Comment by afedchin** [comment]
> @afedchin can you forward me the mail you sent to ffmpeg-devel?

done

**Comment by afedchin** [comment]
https://patchwork.ffmpeg.org/patch/11557/

**Comment by afedchin** [comment]
fixed by #15234 for now
