### ISSUE TITLE
Cleaning library of entries on invalid IP address range takes forever

### ISSUE THREAD

**Issue by kevinfishburne** [xbmc/xbmc#15046]
### Describe the bug

When entries exist in the library whose path is an old NFS share on an invalid IP address range, cleaning the library to remove them takes days, possibly weeks, to finish. The old IP range was 192.168.0.x, and the new IP range is 192.168.1.x.

## Expected Behavior

Cleaning the library should have a reasonable timeout for inaccessible entries and ignore entries inaccessible due to network configuration.

## Actual Behavior

Entries inaccessible due to network configuration have an unreasonable timeout, resulting in the progress bar sitting there for days, possibly working very slowly, possibly not at all. The GUI is unresponsive during this process.

## Possible Fix

Cleaning the library should have a reasonable timeout if for any reason an entry cannot be located, such as five seconds. Further, if an entry is on a network location using an IP address such as a NFS share and that share is inaccessible due to network configuration, it should timeout immediately, as even a five second timeout would take days if there were tens of thousands of entries. Finally, as with updating the library, cleaning the library should take place in the background since it can take some time.

### To Reproduce

1. Configure your network for an IP range.
2. Scan media into your library.
3. Reconfigure your network to a different IP range.
4. Clean the library.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 8.2.5
 - Kodi version: 17.6

**Comment by DaVukovic** [comment]
Please follow the template and provide a debuglog. If you don't do that, this issue might get closed.

Also please update to a recent Kodi Version. LibreELEC 8.2.5 (and therefore Kodi 17.6) is kind of outdated and won't receive any fixes. Please understand the fact, that we don't want to waste our time on problems which might have been fixed in newer versions. So either try LibreELEC 8.90.009 (which ships Kodi 18 rc2) or try one of the Milhouse builds at the forum. 

Generally if you do a clean library and the path to the video can't be found (no matter if the cause is a non existing share or a removed file), the file should be removed from the library. As that's what a "clean library" normally does. Hence we don't recommend to do a clean library at Kodi startup. It might happen, that the network connections isn't established yet and Kodi will begin cleaning your library and if Kodi can't find the path to those videos, they will be dropped from the library. 

Not saying that LE 8.2.5 doesn't have an issue with that. But we need to be sure that newer versions do have the same problem. As 8.2.5 won't receive any updates. So please provide a logfile with a newer Kodi version which shows the same problem

Thanks in advance.

**Comment by kib** [comment]
I am pretty sure this has been fixed in Kodi 18 already.

**Comment by KarellenX** [comment]
Don't do that. OpenELEC is dead and has not been updated in 18 months. Scrapers don't work as well as other issues.

**Comment by DaVukovic** [comment]
Agree

OpeneELEC is horribly outdated and buggy. Please try the 8.90.009 LibreELEC build from here 

http://archive.libreelec.tv

Make sure you took the correct one matching to your hardware.

**Comment by HeresJonny** [comment]
I can confirm such an issue still exists with the latest KODI nightly. Try to add an NFS path. Then stop the NFS sever and start cleaning the library. Or set the Artist info folder to an NFS path, then stop the NFS server and try to change that path. Kodi will take a very long time because it tries to reestablish network connections for each missing path. This is not a bad thing per se but maybe timeout might be set a little lower.

**Comment by HeresJonny** [comment]
I apologize but I recently changed everything from NFS to SMB because there are too many small problems with NFS that are hard to track down, escpecially in conjuntion with MySQL and diffferent OS platforms for Kodi.

**Comment by kevinfishburne** [comment]
Update: Let it run for about five days and it almost got to 50% through. I checked the log after a reset but it only contains information since the last boot and contained nothing useful/interesting. I'll enable debug logging, start the cleaning again and let it run overnight, reset the RPi, then post the debug log. Hopefully it's not cleared upon boot, as there's no way to cancel to cleaning once it starts.

**Comment by Rechi** [comment]
It has been determined that [Banned_addons](https://kodi.wiki/view/Banned_addons) are present on your system. To receive assistance here, these banned items must be removed.
If a clean log is not submitted within 3 days, then the then this issue will be closed.

The Invalid label will be removed if you provide the clean log.

**Comment by DaVukovic** [comment]
No new log, no reaction. Issue closed
