### ISSUE TITLE
Music library performance problems in Leia RC3

### ISSUE THREAD

**Issue by MarkCallow** [xbmc/xbmc#15130]
### Describe the bug
Here is a clear and concise description of what the problem is:

The following big delays always happen in Leia RC3 and did not happen in v17.6 which I was running immediately before updating to Leia RC3.

- 4 - 5 seconds from selecting Music in the top level menu until the Music top level (Artists, Albums, etc.) is displayed.
- 4 - 5 seconds from pressing backspace to return to the Music top level from somewhere else before it is displayed.
- 30 seconds to create a party mode play list. 17.6 took less than a third of that time.
- 5 to 7 seconds to display the playlist: after it has been created, when returning to it from the OSD (backspace) or when picking playlist from pull right options menu in top-level music. It is displayed immediately in 17.6.

During the delay showing the playlist a pop up message box appears titled "Scanning Media Information" and saying inside

```
Loading media information from files
playlistmusic://
```
I have never seen this message box in 17.x.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The top-level music menu should be displayed immediately.
The playlist should be displayed immediately.
Generating a party mode playlist should take less than 10 seconds.

## Actual Behavior

Displaying the top-level music menu takes 4 - 5 seconds.
Displaying the current playlist takes 5 to 7 seconds
Creating a party mode playlist takes 30 seconds.

### To Reproduce

1. Start Kodi
2. In the top-level menu click Music. Observe the time taken for it to be displayed.
3. In the Music menu pick Party Mode in the pull right option menu.
    - Observe the Mixing Drinks pop-up displayed for 30 seconds following by 5 - 7 seconds of empty screen before the playlist is finally displayed.
4. Go full screen so the OSD is displayed.
5. Press backspace and observe the 5 - 7 seconds delay before the playlist is displayed.
6. Press backspace and observe the 4 -5 seconds delay before the Music top-level menu is displayed.
7. Repeat ad nauseum.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/itewixedem

I did the above steps several times while this log was being captured.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

There is also a huge delay the first time you visit the Add-Ons node in the main menu. However unlike the problems I'm reporting with the Music node, this does not repeat.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [x] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: 10.14.2 / macOS Mojave
 - Kodi version: Leia 18.0 RC3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
`22:36:09.858 T:4738180544  NOTICE: Disabled debug logging due to GUI setting. Level 0.`

Not a debuglog. As long as no debug log will be submitted, I'll mark this as invalid.

**Comment by MarkCallow** [comment]
I have uploaded a log with debug logging turned on and updated the link in the bug description. Please remove the invalid label.

**Comment by DaveTBlake** [comment]
Unable to reproduce on Win10 or using LibreElec on RPi, not sure if any team members run on OSX to test. 

Noted that you are using MySQL and it is tempting to blame that but the log shows reasonable DB query times. This implies it is not a db issue at all but the delay is in the internal memory to GUI access.

**Comment by DaveTBlake** [comment]
Yes I agree I don't think this db related.

>If I can find some time this weekend, I'll try but I feel it is a waste of time.

Guess how it feels to be working on issues, especially ones that I can't reproduce. 
Try a portable mode (so not disrupt settings etc.) fresh default installation that is clean of skin changes or addons etc., and produce a log showing the delays. That is the only way I can see to move forwards with this.

**Comment by MarkCallow** [comment]
I reverted to a clean install and scanned my NAS-based library to the default SQLite db. In that set up I did not experience any delays at all. Even "Mixing Drinks" was near instantaneous.

I again reverted to a clean install and copied `advancedsettings.xml` from my saved profile to the clean profile. This causes MySQL on the same NAS as the tracks to be used for both video & music libraries. In this setup there are definitely noticeable short delays in the same places noted above but nothing intolerable, for example about a 1s delay displaying the Music top-level and similar displaying the playlist. I never see the pop-up message box saying `playlistmusic://` when doing this. The worst case is "Mixing Drinks" which takes 10 - 20s. 

So it seems the remote MYSQL db is at least a tiny part of this. I will continue to try to narrow down which part of my saved profile introduces the excessive delays.

**Comment by DaveTBlake** [comment]
Yes accessing a remote MySQL db is inevitably slower than using a local SQLite db, but as you note it is tiny compared to the original issue report. I do wonder what in the profile is contributing.

Seeing the  "Scanning Media Information" message with the slowness is obviously a clue, but not completely sure what to make of it. Kodi does scan tags before playback, and before display in file view if the item is not in the music library. Reading tags on the fly obviously takes time. It makes it sound that the library entires are not being seen for some reason.

**Comment by DaveTBlake** [comment]
Looking in detail at the debug log you provided to see if I can guess where the time is going.
When initially loading party mode in between song 2 and 3
```
11:32:05.550 T:4618053056    INFO: PARTY MODE MANAGER: Adding randomly selected song at 2:[musicdb://songs/50117.flac]
11:32:06.611 T:4618053056   DEBUG: This query part contains a like, we will double backslash in the next field: select idArtist from artist where artist.strArtist like '
11:32:07.781 T:4618053056   DEBUG: SELECT albumview.*,albumartistview.*  FROM albumview  JOIN albumartistview ON albumview.idAlbum = albumartistview.idAlbum  WHERE albumview.idAlbum = 366  ORDER BY albumartistview.iOrder
11:32:08.347 T:4618053056    INFO: PARTY MODE MANAGER: Adding randomly selected song at 3:[musicdb://songs/51600.flac]
```
There is no actual data fetched between the first 2 entries yet this is taking over 1s while similar steps on my system (Win10 but also using MySQL) takes 0.004ms!! Processing entails opening a db connection, and then preparing a query, you could suspect opening is the slow thing. But the next log entry is 1s later (takes 0.3s on mine). In that time artist data has been fetched into local memory and another query prepared (for album data), but using th3e existing connection. Could the prepare be delayed somehow?  Yet other timed queries (involving preparing the SQL and fetching the data) seem reasonable, so possibly not.  What in your profile could be making it worse??

A debug log from the clean profile that is reasonable in speed could be interesting.

**Comment by MarkCallow** [comment]
There is a debug log from the clean profile with my advancedsettings.xml, i.e. using MySQL, at https://paste.kodi.tv/penilafovu. I uploaded this for issue #15129 but it covers invocation of party mode at the start.

**Comment by DaveTBlake** [comment]
Thanks. With clean profile it still takes > 19s to initially load the first 10 songs of party mode, which is better than 37s (your normal profile) but still crazy slow.  But I don't know what is the cause.

Could you paste a debug log from v17.6 of party mode for timing comparison, using your normal profile if fine.

If I make a test build for OSX with extra times written to the log will you b eable to try it?

**Comment by MarkCallow** [comment]
> Could you paste a debug log from v17.6 of party mode for timing comparison, using your normal profile if fine.

How do I revert my database in order to be able to run 17.6 again? From memory, party mode start up in 17.6 wasn't particularly fast either. Probably not that much different from the 19s we're seeing now.

> If I make a test build for OSX with extra times written to the log will you be able to try it?

Yes.

**Comment by DaveTBlake** [comment]
>How do I revert my database in order to be able to run 17.6 again? 

I forgot, messing with MySQL is so much harder than SQLite where you just rename a file, but I would like to compare times rather than rely on memory and feel. There is no revert process, so unless you took a copy of the db then the old 17.6 one is gone. But you could recreate it without removing the v18 db by running 17.6 with a different <name> for the music db in advancedsettings.xml, and then rescanning the library (no scraping of extra artist and album data needed to speed things up).

I will put together a debugging test build sometime later today, I'm really at a loss for the cause at the moment.

**Comment by pkerling** [comment]
> There is no revert process, so unless you took a copy of the db then the old 17.6 one is gone.

No. Old DBs are kept after upgrade (afaik), so you can just start 17.6 and you will get the state of the DB before the upgrade. At least if you didn't manually delete it.

**Comment by a1rwulf** [comment]
> > There is no revert process, so unless you took a copy of the db then the old 17.6 one is gone.
> 
> No. Old DBs are kept after upgrade (afaik), so you can just start 17.6 and you will get the state of the DB before the upgrade. At least if you didn't manually delete it.

I don't think this is true for mysql.

**Comment by MarkCallow** [comment]
I see `xbmc_music60` and `xbmc_music72` databases in mySQL. Is `xbmc_music60` the 17.6 db?

**Comment by a1rwulf** [comment]
> I see `xbmc_music60` and `xbmc_music72` databases in mySQL.

Oh sry, seems I mixedup with my current WIP work.

**Comment by pkerling** [comment]
> Is xbmc_music60 the 17.6 db?

Yes

**Comment by DaveTBlake** [comment]
Sorry for confusion, I just don't use MySQL regularly enough. Yes xbmc_music60 the 17.6 music db

**Comment by MarkCallow** [comment]
I've uploaded a debug log of 17.6, using a clean profile with just my advancedsettings.xml added so as to get my MySQL library, to https://paste.kodi.tv/umaharobej. In this I

1. entered the music top level menu, which took < 1s
2. started party mode, which took about the same 19 seconds as on Leia but the playlist was displayed instantly after Mixing Drinks disappeared.
3. entered full screen OSD. 
4. pressed backspace to return to the playlist, which again was displayed instantly
5. returned to OSD
6. I let the song play then clicked in the progress bar near the end and waited for the transition. The next song info was displayed immediately the new track audio started playing.
7. Repeat steps 4 to 6.

**Comment by MarkCallow** [comment]
I've uploaded a log file for 17.6 using my full profile (that causes problems in Leia) including pkscout's modified Estuary skin to https://paste.kodi.tv/ususixemoj. Behaviour was as described above for 17.6 with clean profile except that the first time I visited the top-level music menu it took 3 or 4 seconds to display.

**Comment by DaveTBlake** [comment]
Thanks for the additional log. I have been looking into this and thought I was onto something, but unfortunately it didn't pan out. So still investigating.

**Comment by MarkCallow** [comment]
Thanks for investigating. I'll be happy to run a test build for you which you asked about earlier. 

In the meantime I am gradually copying things from my saved profile into the new one looking for the extreme slowdown.

Since I pretty much exclusively use party mode, I'll be very happy if we can track down and fix this issue.

**Comment by DaveTBlake** [comment]
I'm still on this @MarkCallow just not getting anywhere fast.  

For now I advise you don't upgrade to RC5 (if you were considering it) as there are MySQL issues with the video db.

**Comment by DaveTBlake** [comment]
I have just noticed that the extra slow partymode (using your profile) log is using partymode.xsp with rules that result in SQL filtering
```
(( NOT  EXISTS (SELECT 1 FROM song_genre, genre 
WHERE song_genre.idSong = songview.idSong AND 
song_genre.idGenre = genre.idGenre AND 
genre.strGenre LIKE '%Christmas%'))) AND 
(( NOT  EXISTS (SELECT 1 FROM song_genre, genre 
WHERE song_genre.idSong = songview.idSong AND song_genre.idGenre = genre.idGenre AND genre.strGenre LIKE '%ChristmasChoral%'))) AND 
((songview.strAlbum NOT  LIKE 'Sleep Deeply' OR songview.strAlbum IS NULL)) AND 
((songview.strAlbum NOT  LIKE 'The Science of Sleep' OR songview.strAlbum IS NULL))
```
but the faster clean profile does not find partymode.xsp and hence filter is empty (all songs). 

I can't see that having a filter clause should cause the overall slowness, the query fetching the first 10 song ids with filter took only 64ms compared to same without that took 1077ms, but it would be good to compare the same smart playlist I guess. 

Can you copy the partymode.xsp into the clean install (of RC4) and fetch a log with party mode run (stopped, clean and rerun) several times.

**Comment by DaveTBlake** [comment]
OK, a test build here http://mirrors.kodi.tv/test-builds/osx/x86_64/kodi-20190112-a731d4f4-DebugPartymode-x86_64.dmg
It will be even slower because of the extra debug line but hopefully will also inlluminate the issue. It uses the Music72 db. @MarkCallow if you can produce debug logs from starting party mode, preferably multiple times, with both clean profile (with partymode.xsp) and your original profile and post links here that would be great.

**Comment by DaveTBlake** [comment]
OK so the partymode.xsp isn't relevent, I didn't think it would be but good to test. 
Test build will be fine - logs using partymode (start/stop a few times) from both clean and original profiles. I believe the RC5 video db issue has now been fixed

**Comment by MarkCallow** [comment]
Here is a log of the test build with the "clean" profile: https://paste.kodi.tv/sohometoje. I started and stopped party mode 4 times.

(I wish you could copy the URL from the Kodi log file uploader add-on. Manual copying is so error prone.)

**Comment by MarkCallow** [comment]
Here is the log with my original profile: https://paste.kodi.tv/uhaqakukoh. Strangely I don't see the extreme slowdown now. Party mode is taking about the same amount of time as with the clean profile.

**Comment by DaveTBlake** [comment]
>Party mode is taking about the same amount of time as with the clean profile.

Yes it is. Which means either my small change was more effective than I thought, or the issue has vanished!

**Comment by MarkCallow** [comment]
The extremely slow party mode start up seems to have vanished. I just tried with RC3 again.

I do notice that the first time I run Kodi and start party mode after changing WiFi connections, it can be extremely slow but after that it  takes the time you're seeing in the logs. When I opened this issue it was always and I wasn't changing WiFi connections. I only started doing that today to see if a 5GHz connection helps vs 2.4GHz. The answer is no.

We're left with just the slow startup of party mode when using MySQL to deal with.

**Comment by DaveTBlake** [comment]
Not really happy with issues that vanish, but it becomes impossible to pursue so I guess should take it as a win. Taking 18s to initialise party mode, while better than 30s is still surprizingly slow. I have another idea to test with that, and since your MySQL setup seems particularly slow it is a good place to explore things. If I get another test build up will you be able to run it?

Regarding changing WiFi connections and slowness, or just slowness sometimes (?), I have to wonder about the impact of the background art loader. If the art for items has not beens displayed for over a day then the loader checks that the image file has not changed and refreshes the texture cache. If the art is over the Wifi then that could contribute.

**Comment by DaveTBlake** [comment]
@MarkCallow can you get a debug log using partymode severakl times for this build http://mirrors.kodi.tv/test-builds/osx/x86_64/kodi-20190116-00be10a3-DebugPartymode-x86_64.dmg please

**Comment by MarkCallow** [comment]
> can you get a debug log using partymode severakl times for this build

Tomorrow. It's late here now.

> Not really happy with issues that vanish,

Me either.

> If the art is over the Wifi then that could contribute.

There is a Textures13.db and a Thumbnails directory that are local. The MySQL database has an `art` table with urls pointing at my network disk where the music is also stored (and the MySQL). I suppose that is the art you are referring to. I wonder if the "background" art loader is really background. Perhaps these is some locking that delays party mode start up.

**Comment by DaveTBlake** [comment]
Just had the odd experience of time taken for initialising party mode in MySQL doubling, from 5s to 10s, but no idea what has triggered that. Using release version, not my test builds, so now I really have a mystery.

**Comment by MarkCallow** [comment]
@DaveTBlake Here is a debug log from the latest test version. Again I started party mode 4 times.

https://paste.kodi.tv/doxelahawi

**Comment by DaveTBlake** [comment]
Thanks. Seems my changes have trimmed 1s off the initialse party mode time which is something, but it is still taking MySQL over 1s to fetch a single record. That is crazy slow. 

Can you tell me about the size of your music db - how many artists, albums, songs?

**Comment by MarkCallow** [comment]
What's a quick way to determine those numbers?

**Comment by DaveTBlake** [comment]
Run some queries using MySQL Workbench or HeidiSQL... :)
But you can just look at the artists, albums and songs nodes in the Kodi GUI each shows how many there are at the bottom

**Comment by MarkCallow** [comment]
1008 artists, 442 albums, 6664 songs.

**Comment by DaveTBlake** [comment]
Thanks. Such a modest library in the scheme of things, so sorry about the slowness.

With help from @MilhouseVH I now understand _why_ the start up of party mode is so slow on MySQL. There is a general MySQL optimizer limitation when using aggregate functions within subqueries as colums in a view. See https://dev.mysql.com/doc/refman/5.7/en/derived-table-optimization.html and https://www.percona.com/blog/2007/08/12/mysql-view-as-performance-troublemaker/ . Along with not using indices on correlated subqueries, this is yet another example of what a poor RDBMS MySQL is, and why users should be surprized by poor performance. 

Since Jarvis the artist datadded has been derived from the songs (rather than be stored directly in the artist table) , and  `artistview` has included a subquery as a column expression. 
```
CREATE VIEW artistview AS SELECT idArtist, strArtist, strSortName, strMusicBrainzArtistID, strType, 
strGender, strDisambiguation, strBorn, strFormed, strGenres, strMoods, strStyles, strInstruments,
strBiography, strDied, strDisbanded, strYearsActive, strImage, strFanart, bScrapedMBID, lastScraped,
(SELECT MAX(song.dateAdded) 
     FROM song_artist INNER JOIN song ON song.idSong = song_artist.idSong 
     WHERE song_artist.idArtist = artist.idArtist) AS dateAdded 
FROM artist
```
As a result even to fetch a single row from `artistview` MySQL scans the entire artist table first. At the start of party mode the artistview is queried separately for each artist of the first 10 songs This is what is taking >1s per song. For comparison on SQLite it takes a mere1ms, yes 1000 times faster and MySQL will be even slower depending on how many artists are in the db.

This general weakness of the MySQL optimiser will be effecting many queries involving albums or artists (views of both have subqueries as columns), but the slowness is particularly noticeable in party mode which is unique in fetching rows one at a time. Elsewhere e.g. songs or artists nodes, many rows are being fetched and so the full table scans that happen are less noticeable. This is ironic as party mode was created as a quick alternative to showing the songs node on large libraries (which is slow for other reasons not the db).

I will look at a fix of party mode to avoid this MySQL issue, if I can achieve an improvement without changes to the schema. But since it has been happening since Jarvis, and I don't know anyone else has noticed or complained, I don't think there is the need to rush into anything risky at the stage in the release cycle of v18.

I intend to review the use of `dateadded` in the music library for v19 anyway, I will certainly keep this issue in mind when I do. If we really want to take efficiency on MySQL db seriously (and fight the pathetic optimiser) without compromising the mainstream SQLite implementation, then there are many areas that can be visited. How far I will be able to get alone that road I don't know, but undertsanding the issue is a good first step.

**Comment by MarkCallow** [comment]
Here's the log from MySQLfast: https://paste.kodi.tv/egacuvocir. I hope I got that right. The Logfile Uploader message box disappeared before I could confirm the URL.

You have more than halved the time taken to start party mode and all the other slowness I described has also disappeared. Thank you, thank you. Please do review `dateadded` for v19. I agree there is no need to risk schema changes for v18.

> happening since Jarvis, and I don't know anyone else has noticed or complained,

I suspect the number if people who use MySQL **and** regularly use party mode is quite small. Also party mode was broken in Jarvis on OS X (as it was then) and was not fixed until Krypton. You always got the same set of songs. There is a bug for it in the old bugzilla. I don't recall many people subscribing to it.

**Comment by pkerling** [comment]
> I intend to review the use of dateadded in the music library for v19 anyway, I will certainly keep this issue in mind when I do. If we really want to take efficiency on MySQL db seriously (and fight the pathetic optimiser) without compromising the mainstream SQLite implementation, then there are many areas that can be visited. How far I will be able to get alone that road I don't know, but undertsanding the issue is a good first step.

I don't know if that's the way to go given that we want to replace pretty much 100 % of the DB implementation anyway. Maybe it would be better to join forces with @a1rwulf on the ORM branch and keep an eye on MySQL performance there? Of course I'm not going to stop you from anything, just as a suggestion :-)

**Comment by DaveTBlake** [comment]
Thanks for testing @MarkCallow , with the changes the start up of party mode is taking only 6s now rather than 19s (assuming the 30s was a horrible anomaly). That confirms I have understood the issue and is satisfying after the initial difficulties repeating your experience.

> Please do review dateadded for v19. I agree there is no need to risk schema changes for v18.

Meanwhile I could apply a workaround (which is what was in the last test build) that does not require schema changes - in effect replacing the use of the view with the artist table where `dateadded` is unneeded. I think it is worthwhile, but want to check with others and do some testing to avoid regressions so it may not get into v18.0

**Comment by DaveTBlake** [comment]
A fix for v18 https://github.com/xbmc/xbmc/pull/15284

**Comment by DaveTBlake** [comment]
Fix merged, so closing issue. Useful to have identified this MySQL optimiser weakness

**Comment by MarkCallow** [comment]
I have identified the difference in my original profile that causes the extreme slowdown. It is having _Allow remote control from applications on other systems_ turned on.

I have posted a debug log to https://paste.kodi.tv/oqupohixir. This was captured using the `MySQLFast` test version you provided. This starts with the setting off. I enter the music node and start party mode then go to full screen after the playlist is displayed. I then go back and forth a few times to the playlist and the the top menu returning to the music node finally stopping party mode. Everything is pretty quick.

I then turn on the setting and repeat the operations. This time entering the music node is slow, party mode startup is extremely slow followed by a big delay before the playlist is shown. Delays are apparent whenever the playlist is displayed, always accompanied by the message box

```
Loading media information from files
playlistmusic://
```

Entering the music node from the main menu is also always slow.

Even after turning off the setting, the delays continue until Kodi is restarted. If I do not turn off the setting the delays will continue to happen after restarting Kodi.

Please reopen this bug or let me know if you prefer me to open a new bug.

**Comment by DaveTBlake** [comment]
That's really interesting @MarkCallow , thanks for continuing to explore the effect of the profile. I will take a look at what is happening.

**Comment by DaveTBlake** [comment]
Although I was unable to reproduce this locally, I think I may have found the cause :)
There is some very silly locking happening in the announcement manager such that any delay in sending announcements prevents anything from adding to the announcement queue. 

@MarkCallow do you know when `Allow remote control from applications on other systems` is enabled what external systems could be listening for Kodi announcements from your system, registered to use JSON API or Python addons perhaps?

But more importantly can you test soon as possible with 
http://mirrors.kodi.tv/test-builds/osx/x86_64/kodi-20190126-c49c7fb2-LockingFix-x86_64.dmg

It is very tight to get this fix into the v18.0 release (probably impossible), but it could solve a number of long standing speed issues so I am going to try, and so the sooner I have feedback the better.

**Comment by MarkCallow** [comment]
`LockingFix` seems to reduce the delays slightly but the problems persist. I've uploaded a log to https://paste.kodi.tv/apojetinip. I entered party mode twice with `Allow remote control from applications on other systems` off then twice with it on moving between playlist, fullscreen OSD, Music and top-level menus during each run.

One behavior change I notice in this version is that the sequence start party mode (which displays the playlist) -> full-screen OSD (from the button on left of the playlist) -> backspace goes back to the Music menu (Artist, Album, etc. nodes). In prior versions backspace would return to the playlist. This only happens the first time after party mode has been started. After having been returned to the Music menu, if I display the playlist again (from the left side slide-in menu), the sequence -> OSD (from the button on left of the playlist) -> backspace correctly returns to the playlist.

> what external systems could be listening for Kodi announcements from your system, registered to use JSON API or Python addons perhaps?

I don't think there are any. IIRC I originally turned on this option when I was trying to get the official Kodi remote apps on iOS & Android to work. I discovered those use remote control via HTTP. I just never turned the option off again. What Python add-ons use this feature?

**Comment by DaveTBlake** [comment]
Not the improvement I was hoping for :(
Oh well, more work to do but unfortunately unable to do so today. Thanks for testing. I will put up another test build on the mirrors if you can pick it up later (I doubt I'll be around to post link)

**Comment by DaveTBlake** [comment]
Well I have found out why 
````
Loading media information from files
playlistmusic://
````
is showing before displaying the Playlists node. There was a hidden bug revealed by another change, easier to fix than find. So far your issue has been very productive even if not all the way to the bottom of it yet.

**Comment by DaveTBlake** [comment]
@MarkCallow another test build, with https://github.com/xbmc/xbmc/pull/15353, https://github.com/xbmc/xbmc/pull/15355 and https://github.com/xbmc/xbmc/pull/15356 included plus extra debug message for announcements is here

Test party mode with `Allow remote control from applications on other systems` enabled/disabled. 

Peripherals are another thing that listen for announcements, any devices plugged in? I hope the extra looging will show exactly where the time is being lost.

**Comment by MarkCallow** [comment]
Here's a log from `AnnounceDebug`: https://paste.kodi.tv/qibocemami.

It shows the full range of issues: delay displaying music node, slow party mode initialization, delay displaying the playlist, delay during song transition and still shows the

```
Loading media information from files
playlistmusic://
```

> One behavior change I notice in this version

I was wrong. The noted behavior is present in RC3. Maybe my memory is faulty and it was this way in 17.6 as well. But I frequently use the route of OSD -> backspace -> playlist -> right click on the current track -> Show Song Information since there is no way to view the _full_ song information of the currently playing song from the OSD - a feature I requested some years ago.

> any devices plugged in?

Only a d/a converter plugged into both USB (where it appears as "C-Media USB Headphone Set") and optical output ports. I use the latter because the former doesn't support > 48kHz sampling.

**Comment by DaveTBlake** [comment]
Many thanks @MarkCallow definative results but disappointing, there is still something I have not found. I will retrace our steps a little, the multiple issues contributing to your slow experience may have mislead me.

**Comment by DaveTBlake** [comment]
OK, @MarkCallow new test build here http://mirrors.kodi.tv/test-builds/osx/x86_64/kodi-20190129-7b92c772-AnnounceDebug-x86_64.dmg with even more logging. You know the drill with enable/disable `Allow remote control from applications on other systems`. 

I'm determined to pin down where the time is going, but so hard since I can't reproduce myself. Still convinced it is something to do with the 42 listeners Kodi has (mine only has 7), but can't see what yet.

**Comment by MarkCallow** [comment]
@DaveTBlake the new log file is too big for paste.kodi.tv. It's 1.2Mb. How can I get it to you?

I've no idea what the 42 listeners are. I suppose they must be add-ons in my Kodi profile. `ls` in my profile's `addons` folder reveals 91 files (not including `packages` and `temp`).

**Comment by MarkCallow** [comment]
Here's the log: https://paste.ubuntu.com/p/hWKwgMjvCm/

There's some stuff at the end you can ignore where I was trying to upload the log with the log uploader add-on.

**Comment by MarkCallow** [comment]
One plug-in that I think is an obvious candidate to be a listener is the Artist Slideshow plug-in so I disabled it but it made no difference to the results. I enabled it again before capturing the log I just posted so you will be comparing apples with apples.

**Comment by DaveTBlake** [comment]
Thanks Mark, the time is clearly lost during opening db - historically this open/close connection is something Kodi does a lot e.g. one for each song in starting party mode. Normally this is taking your system 51ms, but with remote system access enabled it takes 1055ms. 

Lots of other things will be slowed by that not just party mode start up, so little point in my tweeking just party mode

There may be something that can be done in MySQL config to improve things - disable mysql reverse dns see https://www.vionblog.com/skip-name-resolve-to-speed-up-mysql-and-avoid-problems/

Can you let us have details of your MySQL/MariaDB configuration, someone else may be able to spot something there.

**Comment by MarkCallow** [comment]
I'll have a look at the reverse DNS thing, probably tomorrow.

What sort of details to you want about my MariaDB configuration? My server (a Synology DiskStation DS213+) has 2 versions: MariaDB 5 and MariaDB 10. XMBC is using MariaDB 5. Here is what phpMyAdmin says about the server:

```

    Server: MariaDB 5 (Localhost via UNIX socket)
    Server type: MariaDB
    Server connection: SSL is not being used
    Server version: 5.5.59-MariaDB - Source distribution
    Protocol version: 10
    User: root@localhost
    Server charset: UTF-8 Unicode (utf8)
```

The connection referred to above is that between phpMyAdmin, which is also running on the DS, and MariaDB. It is not that between Kodi and MariaDB.

**Comment by MarkCallow** [comment]
> There may be something that can be done in MySQL config to improve things - disable mysql reverse dns see https://www.vionblog.com/skip-name-resolve-to-speed-up-mysql-and-avoid-problems/

It didn't help. In fact it slowed things down both when `Allow remote control from applications on other systems` was set and when it wasn't. It also prevented phpMyAdmin from running. Since Kodi is authenticating as a user local to the DiskStation, I'm not surprised it didn't help. I am surprised it made things worse.

phpMyAdmin is still not running even though I have removed skip-name-resolve. When I click it I just get

```
Synology

The service is disabled now.
```

Sigh!

**Comment by MarkCallow** [comment]
> ```
> Synology
>
>The service is disabled now.
>```
>
>Sigh!

Ahh! The page showing `disabled` was in still my browser cache. Forcing reload fixes it.

**Comment by DaveTBlake** [comment]
Sorry you had problems with php, but --skip-name-resolve  is suggested in multiple articles as help with MySQL slow to open a connection.  The point is for _everything_ to use IP addresses rather than localhost, you may have to change other things for them to continue to work too.

Why open is slower when `Allow remote control from applications on other systems` is enabled does seem specific to your config of server and network, we have not been able to reproduce anything like it. 

With that option enabled Kodi announces a new service over Zeroconf to expose port 9090. When anything connects to MySQL/MariaDB it does a reverse dns and/or zeroconf search on the IP to try to get the name so that it can identify users associated with the host. It seems that having extra Zeroconf announcements is upsetting MySQL. All things happens outside of Kodi.

You could try disabling Zeroconf from within Kodi, that could prove the above.

**Comment by MarkCallow** [comment]
The painful slowness in v18 has returned even without `Allow remote control from applications on other systems` set. It started again the day after I had run the experiment with skip-name-resolve. I do not know why. All I did was add skip-name-resolve and restart the server. Then remove it and restart the server.

Here are 2 debug logs captured with v17.6 and with v18 `AnnounceDebug` so you can compare the difference. These were captured using new bare configs with just my advancedsettings.xml added.

 - v17.6: https://paste.kodi.tv/xulociheli
 - v18.1 AnnounceDebug: https://paste.kodi.tv/xanisejave

The host, network, NAS which hosts the music tracks and MySQL & the version of the MySQL server are the same for both. The only differences are the Kodi version and the version of the Kodi database stored in MySQL. Of course you should not compare party mode initialization as v18.1 has your fixes despite which it has become really slow again. Compare time to display the Music node and time to display the playlist whenever and however you enter them.

**Comment by DaveTBlake** [comment]
I am pretty sure that the remaining v18 slowness you are experiencing is on the MariaDB side of things when creating a connection, not internal to Kodi. If it takes more than 1s to get a connection, something Kodi does multiple times, then many things are going to be slow.

Server caching could be contributing, and the add/remove of **skip-name-resolve** cleared the cache which was allowing v18 to be faster sometimes (e.g. when `Allow remote control from applications on other systems` disabled), but has not refilled. 

Why has this shown up on v18? Well since alpha 1 Kodi uses MariaDB Connector 3.0.3 client library to connect to MariaDB and MySQL databases, replacing the MySQL 5.1.55 client libraries previously used. The combination of that with your 5.5.59 MariaDB on OSX and network setup could be making  Zeroconf/DNS lookup slow to resolve addresses. 

@MarkCallow  it could just come down to needing to update to MariaDB 10.3 but I can not be sure that will solve it. Other users are using v18 with 5.5 MySQL/MariaDB without these connection delays, so it is not just a simple matter of connector compatibilty. 

What settings do you have for MariaDB, any `installdir/mariadb/my.cnf` file? Or running as default config?

You could you try disabling Zeroconf from within Kodi. Kodi announcing over zeroconf could be triggering difficulties in MariaDB ability to resolve addresses over zeroconf.

The other thing to try is using actual IP address as <host> in advancedsettings.xml rather than `DiskStation.local`

I still think setting skip-name-resolve and using IP addresses everywhere rather than zeroconf lookup will help. Slowness to connect with MySQL seems almost always related to resolving addresses.

**Comment by MarkCallow** [comment]
Disabling zeroconf doesn't help.

MariaDB is not running on OSX. It is running on my DiskStation NAS. It has MariaDB 10.0.3 as well as 5. How to I get Kodi to use v10 and how do I migrate my databases from v5?

Here is `my.cnf`. It is the default as far as I know.

```
[client]
port = 3306
socket = /run/mysqld/mysqld.sock

[mysqld]
bind-address = 0.0.0.0
port = 3306
socket = /run/mysqld/mysqld.sock
skip-external-locking
key_buffer_size = 16K
max_allowed_packet = 1M
table_open_cache = 4
read_buffer_size = 256K
read_rnd_buffer_size = 256K
net_buffer_length = 2K
thread_stack = 240K
innodb_data_home_dir = /var/packages/MariaDB/target/mysql
innodb_data_file_path = ibdata1:10M:autoextend
innodb_log_group_home_dir = /var/packages/MariaDB/target/mysql
innodb_buffer_pool_size = 16M
innodb_additional_mem_pool_size = 2M
#innodb_log_file_size = 5M
#innodb_log_buffer_size = 8M
#innodb_flush_log_at_trx_commit = 1
#innodb_lock_wait_timeout = 50
innodb_file_per_table = 1

[mysqldump]
quick
max_allowed_packet = 16M

[mysql]
no-auto-rehash

[myisamchk]
key_buffer_size = 8M
sort_buffer_size = 8M

[mysqlhotcopy]
interactive-timeout

# Please add your custom configuration to here:
!include /var/packages/MariaDB/etc/my.cnf
```

There is no custom configuration file.

**Comment by DaveTBlake** [comment]
A mix of things have contributed to the slowness of v18 you originally reported. Several have been fixed -  query of view with aggregate,  announcement and application message queue locks - to the benefit of all Kodi users.  What remains is slowness opening db connection, it taking over 1s each time, that has become more persistent since you reset your server.

As Zeroconf setting makes no difference, and  `Allow remote control from applications on other systems` no longer changes anything either I think we have to conclude that it is not anything that Kodi does that is  triggering such slow db opening connection. The MariaDB connector library used by v18 could be making a difference, but that library is external to Kodi.

>It is running on my DiskStation NAS. It has MariaDB 10.0.3 as well as 5. How to I get Kodi to use v10 and how do I migrate my databases from v5?

Sorry I have no personal experience of running MariaDB on a NAS dive so the guidence I can give is limited. I believe Synology has integrated docker support so I suppose the different MariaDB server versions you say are installed are in containers that are either listening on different IPs or different external ports.  You will have to pursue that yourself I'm afraid.

All the Kodi guides on using MySQL/MariaDB say to use IP address of the server in advancedsettings.xml e.g.  `<host>192.168.1.30</host>`, and I recommend that you do that rather than the shortcut  `diskstation.local`.  Assign your NAS a fixed IP address and use that. Use of IP addresses avoids resolving names and is known to be quicker. This should be accompanied by adding `skip-name-resolve` to the my.cnf file, again as recommended.

Some notes here https://kodi.wiki/view/MySQL/Setting_up_MySQL
https://kodi.wiki/view/MySQL/Advanced_notes
https://forum.kodi.tv/showthread.php?tid=329046

Looking at other settings in my.cnf  `innodb_buffer_pool_size` could be bigger if you have the memory. MariaDB recommend 80% of available in multiples of 1G. I will see if anyone else on the team has any other suggestions.

If you are thinking but it works for v17 and if it doesn't for v18 then that is a Kodi problem all I can remind you is that MySQL/MariaDB server use for Kodi is an experiemental feature.  There are just too many server versions on too many platforms, all potentailly behave differently. It may have worked by accident, or the MariaDB connector library version change could have exposed an issue with your setup that was previously masked. The remaining slowness is happening on the MariaDB side of things, all I can suggest is that you move towards a more recommended configuration using IP addresses and that should help.

**Comment by MarkCallow** [comment]
The MariaDB versions are listening on different ports so I can just change the port in advancedsettings.xml to use the new version. Now I have to figure out how to migrate the databases. I don't suppose I can just copy them, i.e. that v10 will be okay with a v5 written DB. After I've switched databases, I will try using IP addresses. I will not be able to increase the innodb_buffer_pool_size much but I will try.

Thank you for your extensive help @DaveTBlake. I am glad that some Kodi fixes came out of the effort.

Rather off topic, but are there any plans to sign the Kodi macOS binaries? I ask because due to some corruption in the System Policy database (I think) on one of my Macs, I cannot get macOS to accept the permission needed to let unsigned Kodi run.

**Comment by DaveTBlake** [comment]
How much compatibility there is between MariaDB v15 and v10 I don't know, but you should be able to "export" the schema + data as a series of SQL statements that you can then run in v10. At least that approach works for MySQL.

No plans for signed macOS binaries AFAIK, but I will ask

**Comment by MarkCallow** [comment]
Migrating the db was easy. Export from v5 and import to v10, _after_ creating the user specified in advancedsettings.xml.

It seems a little faster but still not as fast as Kodi 17.6. I haven't been able to do much exploration of performance because I have been restoring parts of the data in my library. Many of the folder.jpgs were overwritten somehow. I suspect the default profile is set to download album thumbs from the internet. The modification dates correspond to when I created those 2 debug logs using bare configs. Although in 2 cases folder.jpg was rewritten with the contents of a non `Cover (Front)` tag from the audio file, e.g, the `Cover (back)` contents were used. I have no explanation for that.

**Comment by MarkCallow** [comment]
Since switching to MariaDB 10, pretty much every time I run Party Mode it aborts after some time, 20 minutes or so, saying it cannot connect to the database. However Kodi is playing music from the same NAS device and continues until it exhausts the playlist established before PM aborted. So it is only the db connection that is lost. This happened only very  occasionally with MariaDB 5. I will have to run with debug logging and see if I can learn more.

**Comment by MarkCallow** [comment]
I final had time to do some more experimentation. I changed `advancedsettings.xml` to use the IP address instead of `DiskStation.local`. Performance is dramatically better. Going to the Music top node takes 1 second or less, not quite as fast as with a local DB but almost. Party Mode start up takes only 2 or 3 seconds. This is using release v18 so doesn't even have the most recent fixes.

Turning on `Allow remote control via HTTP`, Zeroconf support and UPnP support does not affect performance. However turning on `Allow remote control from applications on other systems` continues to make everything slow. I have not tried the combo of IP address and `skip-name-resolve` based on the issues I had last time I tried the latter and because the only resolution MariaDB will be doing is to `localhost`. Since I don't actually need this remote control setting this is not really a problem for me.

I'll keep you posted on whether issues continue with Party Mode aborting. I have Kodi running with debug logging enabled.

**Comment by DaveTBlake** [comment]
So IP address is the way to go, not `DiskStation.local`, for performance and v18.1 will be a little faster too.

I think that the slowdown when `Allow remote control from applications on other systems` is enabled would be solved by using `skip-name-resolve` in MySQL, but up to you if you don't need this Kodi setting enabled so don't want to try that.

I have no idea about party mode aborting, but provide more info as and when you can.

**Comment by DaveTBlake** [comment]
Issue resolved back Feb 2019
