### ISSUE TITLE
Settings Across Categories

### ISSUE THREAD

**Issue by goocreations** [xbmc/xbmc#15252]
### Describe the bug
According to [https://kodi.wiki/view/Add-on_settings](https://kodi.wiki/view/Add-on_settings):

> Comparisons CANNOT be made across category/page boundaries. If one needs to compare to a setting on a different page, a copy of the setting with the same id can be placed on the page where the comparison is to take place and then hidden by setting visible to 'false'. The value is automatically updated when the setting on the other page is updated.

If you want to reference a certain setting from another page, you simply create a copy of that setting with the same ID in a different category. This worked perfectly in Kodi 17, but not at all in Kodi 18. It seems that if you create the non-visible copy of the setting and place it in a category **BEFORE** the actual visible element, the acutal visible element is never shown in the dialog.

## Expected Behavior
The setting's element should show in the settings dialog so that the user can change the value.

## Actual Behavior
The setting's element is not visible in the settings dialog so that the user cannot change the value.

## Possible Fix
I think that Kodi 18 uses the "visible" of the **FIRST** element in the XML, instead of checking if there are multiple elements with the same ID and applying their own respective "visible" attribute.

### To Reproduce
```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<settings>
	<category label="category 1">
		<!-- The hidden copy of the setting to be referenced somewhere here in category1. It is hidden as expected by visible="false". -->
		<setting id="test" type="bool" visible="false" />
	</category>
	<category label="category 2">
		<!-- This is the actual setting that the user adjusts. This element is invisible in the settings dialog. Maybe Kodi uses the visible="false" from the previous reference . -->
		<setting id="test" type="bool" label="Test Setting" default="false" />
	</category>
</settings>
		
```

### Debuglog
Nothing in log.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Window 10, Window 7, Ubuntu 16, Ubuntu 17, Ubuntu 18
 - Kodi version: Kodi 18 (this bug is not present in older versions)

**Comment by ronie** [comment]
i can confirm this issue.

the re-use of settings was supposed to be fixed by https://github.com/xbmc/xbmc/pull/15015
but apparently not all use cases were covered.

@enen92

**Comment by enen92** [comment]
I'll take a look but not sure if I can solve the issue in reasonable time for v18. PR #15015 solved the issue of reusing the setting but that means all the fields of the setting are also reused. Means the setting is just a pointer and the visibility conditions of the first one are reused.

**Comment by goocreations** [comment]
@enen92 Understood. But will be sad if this doesn't make it to the final Leia release. This bug will cause settings in a lot of addons to be hidden which could make some of them unusable. If all else fails, it would be better to just make all related settings visible instead of hidden. Will look ugly in the dialog, but then at least users will be able to change the settings.

**Comment by MartijnKaijser** [comment]
Never claim something will affect a lot of addons because you cannot proof that

**Comment by goocreations** [comment]
This bug seems to extend beyond the "visible" attribute.

If you for instance have a copy of the same bool element across 2 categories, and then you set the value of that element via Python. Although both elements will get the updated value, you can only **query** the first element's value from another element. For instance:

```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<settings>
	<category label="category 1">
		<setting id="test" type="bool" visible="false" />
		<setting id="test_c_1" type="bool" visible="eq(-1,true)" />
	</category>
	<category label="category 2">
		<setting id="test" type="bool" visible="false" />
		<setting id="test_c_2" type="bool" visible="eq(-1,true)" />
	</category>
</settings>
```

In this case, if you set "test" value to TRUE in Python, only "test_c_1" will become visible, but "test_c_2" will stay invisible. Even if "test_c_2" checks if the value is FALSE:

`<setting id="test_c_2" type="bool" visible="eq(-1,false)" />`

it still stays hidden. I guess that the value of the 2nd "test" element cannot be read at all, so the 2nd eq condition evaluates to FALSE, irrespective of whether "test_c_2" is TRUE or FALSE.

**Comment by Zomboided** [comment]
I'm testing with the released Kodi 18 build and my addon with needlessly complicated settings took a dump when accessing settings.xml

I created a much simpler test case which shows that reuse of IDs within a catagory is still broken, and reuse of IDs across catagories is broken.

Here's the xml I'm using (renamed to .txt so I could upload it), fully commented as to where the is badness happening
[settings.xml.txt](https://github.com/xbmc/xbmc/files/2828906/settings.xml.txt)

And here's my full test case with a settings tab that's working (using different IDs), an a settings tab that's broken (re-using IDs).

[service.test.settings-0.0.1.zip](https://github.com/xbmc/xbmc/files/2828911/service.test.settings-0.0.1.zip)

When accessing the log, here are the issues that appear that go away if I avoid using the same ID multiple times.

16:08:46.212 T:8712 WARNING: CAddonSettings[service.test.settings]: cannot reference separator setting in old setting condition "eq(5,true)" for "password_visible"
16:08:46.212 T:8712 WARNING: CAddonSettings[service.test.settings]: failed to parse visible condition "eq(5,true)" of old setting definition for "password_visible"
16:08:46.212 T:8712 WARNING: CAddonSettings[service.test.settings]: cannot reference separator setting in old setting condition "eq(2,true)" for "password_enable"
16:08:46.212 T:8712 WARNING: CAddonSettings[service.test.settings]: failed to parse enable condition "eq(2,true)" of old setting definition for "password_enable"

16:08:51.623 T:8712   DEBUG: CSettingsManager: requested setting (#cross_catagory) was not found.
16:08:51.623 T:8712 WARNING: CSettingDependencyCondition: unable to check condition on unknown setting "#cross_catagory"
16:08:51.624 T:8712   DEBUG: CSettingsManager: requested setting (#show_reuse) was not found.
16:08:51.624 T:8712 WARNING: CSettingDependencyCondition: unable to check condition on unknown setting "#show_reuse"
16:08:51.624 T:8712   DEBUG: CSettingsManager: requested setting (#cross_catagory) was not found.
16:08:51.624 T:8712 WARNING: CSettingDependencyCondition: unable to check condition on unknown setting "#cross_catagory"
16:08:51.624 T:8712   DEBUG: CSettingsManager: requested setting (#show_reuse) was not found.
16:08:51.624 T:8712 WARNING: CSettingDependencyCondition: unable to check condition on unknown setting "#show_reuse"

Here's the full log
[kodi.log](https://github.com/xbmc/xbmc/files/2828925/kodi.log)

I can see you're already aware of this issue and 15015, but hopefully this helps you fix it.

**Comment by reddit-reaper** [comment]
just curious but would this also cause an issue where settings window refuses to scroll past a certain point if using arrow keys and forced to use painfully slow scroll wheel to get past it?

**Comment by basrieter** [comment]
The latter is related to having 100+ settings in a category: https://github.com/xbmc/xbmc/pull/14154

**Comment by reddit-reaper** [comment]
Yeah i saw that the pr is already available to merge. Question is why it hasn't been merged yet if the fix is so easy. This was never an issue before

**Comment by bigretromike** [comment]
This bug is still present (stable 18.2, matrix)

Current workaround would be make in-logic setting design with "bad UI" to make each setting be visible before referring to it.

**Comment by Montellese** [comment]
@Zomboided thanks for the test add-on. That should make it easier to reproduce and test the issues. I have a few questions / remarks:
* You "define" `password_visible` and `password_enable` twice within the same category but they have different `"default"` values. How does that make sense?
* The empty label problem should be fixed in #16660 
* the multiselect add-on problem should be fixed in #16660 

I'll try to have a look at the issues.

**Comment by Zomboided** [comment]
@Montellese 
Yeah, it doesn't :-)  I suspect I copied this from the working tab when i was trying to generate the test case.  Typically I'd only set the default on the first instance anyway.
I just went back and changed my copy of the test case to have a single default and the problem I was referencing in the XML still exists.
Thanks for the update on the other two issues, and generally, your work on Kodi.

**Comment by Montellese** [comment]
Yeah I didn't expect that removing one of the default values would solve the problem. I just wanted to check why this would make sense but obviously it was a mistake.

**Comment by Montellese** [comment]
So I finally had some time to think about a better approach / solution to settings that are re-used multiple times and I may have come up with something that is working. The implementation is located in the [addon_settings_references](https://github.com/Montellese/xbmc/tree/bug/addon_settings_references) branch in my repository. It is not completely finished but ready for testing.

With this implementation the example add-on from @Zomboided is working (except for hiding separators) perfectly fine AFAICT.

It would be great of some add-on developers could test this implementation and let me know if it solves their issues or not. Thanks.

**Comment by basrieter** [comment]
Do you have a build for that?

**Comment by Montellese** [comment]
@basrieter: A build is running at https://jenkins.kodi.tv/view/Automation/job/BuildMulti-Choice/274/. Win64 is already available at http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20190929-01fc1ab7-bug-addon_settings_references-x64.exe. The others should follow soon.

**Comment by Zomboided** [comment]
Just tested the Win64 build (thanks for the link).  The visability of things (separator aside) is working as I'd expect, as is the multiple list selection being displayed.  Regarding the reuse of values, this is not working for me, either within catagories, or across catagories.

I modified my test case attached (obviously needs a rename) - you can reuse it with the addon I posted earlier - where the password fields and the bool to display them are reused multiple times both within the 'Working' and 'Broken' tabs (which are now just badly named anyway!)

[settings.xml.txt](https://github.com/xbmc/xbmc/files/3669254/settings.xml.txt)

**Comment by Montellese** [comment]
@Zomboided thanks for the feedback. Did you also try it with your original `settings.xml` you posted above? Because that is working perfectly fine for me now.
* I can change the value of `cross_catagory` in the `Working` category and the `enable` condition of both `some_random_text_1` in the `Working` and of `some_random_text_3` in the `Broken` category are updated.
* I can toggle `show_reuse` in both categories and it updates the `visible` condition of both `some_random_text_2` in the `Working` and of `same_random_text_4` in the `Broken` category.
* Toggling `show_password_broken` properly updates the `enable` and `visible` conditions of the two `password_visible` and the two `password_enable` settings in the `Broken` category.

I will give your updated `settings.xml` a try ASAP.

**Comment by Zomboided** [comment]
I just tried cross_catagory as I'd not changed that - I don't see the change applied, either if I move between tabs, or click ok and go back.  I've also tried to click 'Default' across the catagories to reset everything in case there's some old rubbish in there.

Here's the build I'm running.

![image](https://user-images.githubusercontent.com/17079525/65857634-247a4500-e35c-11e9-9ac3-35bd9bc3f6c3.png)

Let me try using the original settings I posted

**Comment by Zomboided** [comment]
Nope, original settings still broken for me too for cross_catagory, in that it doesn't update the value in the other catagory.  I should have said that the enabling/disabling of the value below it if it's null works just fine now.

The show_reuse is working just fine!  The difference between this and the new test case is that the second use of it is hidden, which is maybe a more likely use case (I think this is how I had the settings in my real addon before I started having to mess wtih them)

**Comment by Montellese** [comment]
How can you see whether `cross_category` is updating on the `Broken` category? It's not visible in the settings dialog so there's no way to tell from the UI whether it has been updated or not.

**Comment by Zomboided** [comment]
Ok, I tested this too quickly and not sure how I saw different results
earlier (work day, not focused enough maybe....sorry)

I now see this working, both with cross_category marked as visible, and
both enabled and disabled.
I also see the password working when I change it on one screen, but not on
the other in the new test case.

The only thing I don't see working is the show_reuse.  In the working tab,
it shows the text when it's enabled.
In the broken tab, it never shows the text regardless of the setting in the
working tab.

**Comment by Montellese** [comment]
Just tested your new `settings.xml` myself:
* `cross_category` works fine to enable / disable the next line both under `Working` and `Broken`
* changing the value of `password_visible` / `password_enable` either in the `Working` or `Broken` category properly updates the copies / references
* something is wrong with the `hidden` option of `password_visible` and `password_enable` in the `Broken` category. In the `Working` category everything is fine.
* `show_password_broken` works fine in and across both categories
* `show_reuse` is working perfectly fine here. If I disable it on the `Working` category the next line disappears both under `Working` and `Broken`. But the separator above it is still displayed.

I'll have a look at the `hidden` option and why it is not properly used. This might actually be related to the missing functionality I mentioned above.

PS: You again specified multiple default values for the same setting for `password_visible` and `password_enable`.

**Comment by Zomboided** [comment]
I don't see where I'm specifying multiple default values in the updated version of the test?  Either way, I see the hidden problem too...but interestingly if you make one of the other values hidden, it works anyway.

Do you have an updated Win64 build?  I'm happy to take that for a run after blowing away the config - I'm not always seeing the same results as you (paying attention this time)

**Comment by Montellese** [comment]
Concerning the multiple default values: In your latest `settings.xml` (and the one before) for the setting with ID `password_visible` you specify a default value of
* `passw0rd_1` on line 12
* `passw0rd_2` on line 13

and for the ID `password_enable` you specify a default value of
* `passw0rd_3` on line 16
* `passw0rd_4` on line 17

**Comment by Montellese** [comment]
New test builds are being built at https://jenkins.kodi.tv/view/Automation/job/BuildMulti-Choice/275/.

**Comment by Montellese** [comment]
@Zomboided just tried your latest `settings.xml` here and everything looks OK for me. Please let me know if you see different results.

**Comment by Montellese** [comment]
I just added a commit that should also fix the problem with the visibility of the separator and its label. I've started a new test build on https://jenkins.kodi.tv/view/Automation/job/BuildMulti-Choice/276/. It should be ready in an hour or so.

**Comment by Montellese** [comment]
Did anyone have time to give this a go?

**Comment by Zomboided** [comment]
Hello, not yet, travelling with work at the moment. Will try and get to this either at the weekend or early next week

**Comment by Zomboided** [comment]
Is there a link to a Windows 64 build?  The /276/ is not found

**Comment by Montellese** [comment]
Looks like the test build has already been deleted. I've started a new one for Win64: https://jenkins.kodi.tv/view/Automation/job/BuildMulti-Choice/279/.

**Comment by Montellese** [comment]
@Zomboided the test build should be available at http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20191009-c0871826-bug-addon_settings_references-x64.exe

**Comment by Zomboided** [comment]
This is fine for me, thanks.
The only issue I saw was that trying to launch an add-on from the icon on the add-on screen failed, whereas this works fine on 18.4.  If this new behaviour is unrelated to anything you've done here (it certainly wasn't going near a settings screen) then let's close out the problem you've fixed.

**Comment by Montellese** [comment]
Thanks for taking the time to test it and for your feedback. Looks like it's ready to be put into a PR.

I'm not aware that I've touched any non add-on settings specific stuff.

**Comment by Montellese** [comment]
I've created the pull request at #16773.
