### ISSUE TITLE
Kodi ignores custom joystick.xml in special://home/userdata/keymaps/

### ISSUE THREAD

**Issue by Wintermute0110** [xbmc/xbmc#15316]
### Describe the bug

I use a gamepad exclusively to control Kodi and hence it is important to configure it to suit my needs.

I create a custom file `special://home/userdata/keymaps/joystick.xml`, based on the default `joystick.xml` found in the system directory. Kodi totally ignores `joystick.xml` in the userdata directory, located in `/home/kodi/.kodi/userdata/keymaps/`. A workaround I found is to delete the default `joystick.xml` in the system directory (Kodi installation directory), however this file will be recreated any time Kodi is updated.

In the debug log, I can verify that Kodi loads both XML configuration files when both are present and Kodi ignores the custom configuration in the XML file in the userdata directory.

## Expected Behavior

The joystick XML file in the userdata directory must override the default XML file in the system directory.

## Actual Behavior

Kodi ignores the configuration in the userdata directory when a default configuration exists in the system directory.

## Possible Fix

N/A

### To Reproduce

* Install Kodi and use a gamepad to control it.

* Create a custom `joystick.xml` file in `/home/kodi/.kodi/userdata/keymaps/` directory to override the default `joystick.xml` in Kodi installation.

* Kodi totally ignores the custom configuration file `joystick.xml`.

### Debuglog

My custom [joystick.xml](https://paste.kodi.tv/xagikegitu.kodi) in `/home/kodi/.kodi/userdata/keymaps/joystick.xml`.

[Kodi debug log](https://paste.kodi.tv/tevekerofa.kodi) when default `joystick.xml` has been deleted and custom joystick configuration works.

[Kodi debug log](https://paste.kodi.tv/zasifiyeca.kodi) when default `joystick.xml` is present and custom `joystick.xml` is totally ignored.

### Screenshots 

N/A

### Your Environment

Linux Ubuntu Xenial, Kodi version from master commit `3aac935a7e712e7a303763c649351d1569241cae`.

**Comment by DaVukovic** [comment]
> I will include debug logs if necessary.

Woudl be best, otherwise your issue will be closed in 3 days as a debuglog is always mandatory

Next thing which might be necessary to provide is a paste of your changes you've done to the custom joystick.xml (next to the debuglog). 

As you have completely ignored to follow our template which would get us more info of
- the hardware in use
- the platform you are using Kodi on
- the Kodi version you are using
- and many other details

I will mark this issue as "invalid" until you have provided the missing informations.

**Comment by Wintermute0110** [comment]
No problem, I will include logs tonight.

> As you have completely ignored to follow our template which would get us more info of
>
>    the hardware in use
>    the platform you are using Kodi on
>    the Kodi version you are using
>    and many other details

Have I? I wrote my platform is Linux, Kodi is compiled from master and wrote down the commit ID. Tonight I will wrote down the gamepad I'm using. Is there anything else you need?

**Comment by Wintermute0110** [comment]
OK, I have included my custom `joystick.xml`, debug logs when the problem happens and when it does not happen and improved the bug description. Please tell me if you need something else.

**Comment by garbear** [comment]
@Wintermute0110 See https://github.com/xbmc/xbmc/pull/15347

**Comment by DocMAX** [comment]
I can confirm this bug!

**Comment by memzila** [comment]
Same issue here with shield 2015 pro

**Comment by funkymaster** [comment]
I have got the same problem here on my win7 x64 machine with v18.1 x64. My custom joystick.xml can be found on: https://paste.kodi.tv/ozajecisar.kodi Please notify if someone needs a debug log.

**Comment by tstack77** [comment]
Same issue, shield pro 2017

**Comment by arigit** [comment]
same issue, kodi 18.3, ubuntu 18.04

**Comment by arucard21** [comment]
To clarify why this was closed, this is now fixed by #16521 which should be available in Kodi v19 Matrix.

**Comment by marvin2k1** [comment]
Hello, i have this problem on kodi 20 in xubuntu, remote keymap works but not joystick.xml on log file we can see:
 info <general>: Loading special://masterprofile/keymaps/joystick.xml
2024-07-11 23:26:55.573 T:16506   error <general>: Error getting keymap root: special://masterprofile/keymaps/joystick.xml
(...)
 info <general>: Loading special://profile/keymaps/joystick.xml
2024-07-11 23:26:55.574 T:16506   error <general>: Error getting keymap root: special://profile/keymaps/joystick.xml
2024-07-11 23:26:55.574 T:16506    info <general>: Loading special://profile/keymaps/remote.Hama.MCE.xml

Joystick keymap looks like two times instead one and the first attemp profile have bad path (masterprofile) instead (profile)

**Comment by garbear** [comment]
@marvin2k1 It looks like you have an invalid XML file. `Error getting keymap root` means that the root &lt;keymap> tag isn't found.

**Comment by marvin2k1** [comment]
You are rigth, there was a problem, i just edit original /usr/share/kodi/system/keymap/joystick.xml and this works, but still custom /home/.Kodi/userdata/keymap/joystick.xml still not working. i will give another test round.

**Comment by CaeruleanTrigon** [comment]
This problem exists for me in 21.2-Omega, I've tried placing the xml in multiple places and the only one that works is replacing the one in '/system/keymaps/'. Tested in the fedora flatpak, and Libreelec, except the system joystick.xml is read only in Libreelec so I haven't been able to use that as a work around.

Steps to reproduce are: 
- Copy joystick.xml from /system/keymaps/ to /userdata/keymaps
- Comment out / remove control lines from <global> and/or <FullscreenVideo> 
- Reboot and try the controls

Here's snippets from the logs showing the file being found and loaded with no error messages, and the modified section of the joystick.xml file. The modifications do work when the built in joystick.xml file is modified, but don't when placed in a /userdata/keymaps/ folder, either for the master user or a user profile.

kodi.log:
> 2025-08-15 00:53:40.778 T:7        info <general>: -----------------------------------------------------------------------
> 2025-08-15 00:53:40.778 T:7        info <general>: Starting Kodi (21.2 (21.2.0) Git:20250115-d1a1d48-dirty). Platform: Linux x86 64-bit
> 2025-08-15 00:53:40.778 T:7        info <general>: Using Release Kodi x64
> 2025-08-15 00:53:40.778 T:7        info <general>: Kodi compiled 2025-05-25 by GCC 14.2.0 for Linux x86 64-bit version 6.6.17 (394769)
> 2025-08-15 00:53:40.778 T:7        info <general>: Running on Freedesktop SDK 24.08 (Flatpak runtime), kernel: Linux x86 64-bit version 6.14.11-300.fc42.x86_64
(...)
> 2025-08-15 06:53:41.028 T:7        info <general>: Loading special://xbmc/system/keymaps/appcommand.xml
> 2025-08-15 06:53:41.028 T:7        info <general>: Loading special://xbmc/system/keymaps/customcontroller.AppleRemote.xml
> 2025-08-15 06:53:41.028 T:7        info <general>: Loading special://xbmc/system/keymaps/customcontroller.Harmony.xml
> 2025-08-15 06:53:41.028 T:7        info <general>: Loading special://xbmc/system/keymaps/customcontroller.SiriRemote.xml
> 2025-08-15 06:53:41.028 T:7        info <general>: Loading special://xbmc/system/keymaps/gamepad.xml
> 2025-08-15 06:53:41.028 T:7        info <general>: Loading special://xbmc/system/keymaps/joystick.xml
> 2025-08-15 06:53:41.028 T:7        info <general>: Loading special://xbmc/system/keymaps/keyboard.xml
> 2025-08-15 06:53:41.029 T:7        info <general>: Loading special://xbmc/system/keymaps/keymap.xml
> 2025-08-15 06:53:41.029 T:7        info <general>: Loading special://xbmc/system/keymaps/mouse.xml
> 2025-08-15 06:53:41.029 T:7        info <general>: Loading special://xbmc/system/keymaps/remote.xml
> 2025-08-15 06:53:41.029 T:7        info <general>: Loading special://xbmc/system/keymaps/touchscreen.xml
> 2025-08-15 06:53:41.030 T:7        info <general>: Loading special://masterprofile/keymaps/gamepad.xml
> 2025-08-15 06:53:41.030 T:7        info <general>: Loading special://masterprofile/keymaps/joystick.xml
> 2025-08-15 06:53:41.030 T:7        info <general>: Loading special://profile/keymaps/gamepad.xml
> 2025-08-15 06:53:41.030 T:7        info <general>: Loading special://profile/keymaps/joystick.xml

joystick.xml:
```
<keymap>
  <global>
    <joystick profile="game.controller.default">
      <a>Select</a>
      <a holdtime="500">ContextMenu</a>
      <b>Back</b>
      <x>ContextMenu</x>
      <y>FullScreen</y>
      <start>ActivateWindow(PlayerControls)</start>
      <back>ActivateWindow(Home)</back>
      <guide>ActivateWindow(Home)</guide>
      <up>Up</up>
      <down>Down</down>
      <right>Right</right>
      <left>Left</left>
      <!--
      <leftthumb>Screenshot</leftthumb>
      <rightthumb>ActivateWindow(ShutdownMenu)</rightthumb>
      <lefttrigger>ScrollUp</lefttrigger>
      <righttrigger>ScrollDown</righttrigger>
      -->
      <leftbumper>ScrollUp</leftbumper>
      <rightbumper>ScrollDown</rightbumper>
      <leftstick direction="left">Left</leftstick>
      <leftstick direction="right">Right</leftstick>
      <leftstick direction="up">Up</leftstick>
      <leftstick direction="down">Down</leftstick>
      <!--
      <rightstick direction="left">VolumeDown</rightstick>
      <rightstick direction="right">VolumeUp</rightstick>
      <rightstick direction="up">VolumeUp</rightstick>
      <rightstick direction="down">VolumeDown</rightstick>
      -->
    </joystick>
  </global>
  <Home>
    <joystick profile="game.controller.default">
      <b>Back</b>
      <b holdtime="500">ActivateWindow(ShutdownMenu)</b>
    </joystick>
  </Home>
  <FileManager>
    <joystick profile="game.controller.default">
      <rightbumper>Highlight</rightbumper>
    </joystick>
  </FileManager>
  <MusicPlaylist>
    <joystick profile="game.controller.default">
      <leftbumper>Delete</leftbumper>
    </joystick>
  </MusicPlaylist>
  <Music>
  </Music>
  <FullscreenVideo>
    <joystick profile="game.controller.default">
      <a>Pause</a>
      <b>Stop</b>
      <x>OSD</x>
      <start>Info</start>
      <back>FullScreen</back>
      <guide>OSD</guide>
      <up>ChapterOrBigStepForward</up>
      <down>ChapterOrBigStepBack</down>
      <right>StepForward</right>
      <left>StepBack</left>
      <!--
      <leftthumb>ShowSubtitles</leftthumb>
      <rightthumb>AspectRatio</rightthumb>
      <lefttrigger>AnalogRewind</lefttrigger>
      <righttrigger>AnalogFastForward</righttrigger>
      <leftbumper>AnalogRewind</leftbumper>
      <rightbumper>AnalogFastForward</rightbumper>
      <leftstick direction="left">AnalogSeekBack</leftstick>
      <leftstick direction="right">AnalogSeekForward</leftstick>
      <leftstick direction="up">noop</leftstick>
      <leftstick direction="down">noop</leftstick>
      -->
    </joystick>
  </FullscreenVideo>
```

**Comment by arucard21** [comment]
In case it helps narrow down the problem, I've used a custom config in `.kodi/userdata/keymaps/joystick.xml` with a very similar content as above with LibreELEC on a Rasperry Pi 5 using a PS5 (DualSense) controller. It's worked just fine so far and the customized controls are detected correctly. There's also no error about loading the keymap XML file in the log.

Here's the log output with the system details:
```log
2025-07-13 16:16:27.285 T:885      info <general>: Starting Kodi (21.2 (21.2.0) Git:21.2-Omega). Platform: Linux ARM 64-bit
2025-07-13 16:16:27.285 T:885      info <general>: Using Release Kodi x64
2025-07-13 16:16:27.285 T:885      info <general>: Kodi compiled 2025-01-20 by GCC 13.2.0 for Linux ARM 64-bit version 6.6.70 (394822)
2025-07-13 16:16:27.285 T:885      info <general>: Running on LibreELEC (official): 12.0.2, kernel: Linux ARM 64-bit version 6.6.70
```
