### ISSUE TITLE
ListItem.Absolute(0) is returning the focused item

### ISSUE THREAD

**Issue by sualfred** [xbmc/xbmc#15442]
### Describe the bug
ListItemAbsolute(0) is partly broken in Leia and returning informations based on the focused instead of the absolute item. 

ListItemAbsolute(1) works.

This is only happening in media windows with viewtypes. It works as expected on other containers outside of the library.

With Container(id).ListItemAbsolute(0) or Container.ListItemAbsolute(0) it is working again.

## Expected Behavior
ListItemAbsolute(0).[infolabel] should return the labels of the absolute position

## Actual Behavior
ListItemAbsolute(0).[infolabel] is going to return the label of the focused position

### To Reproduce

Add a label to myvideonav.xml in Estuary:
<control type="label">
<label>$INFO[ListItemAbsolute(0).Label]</label>
</control>

### Your Environment
Tested operating systems:
 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [x] Windows UWP

 - Operating system version/name:
 - Kodi version: v18 stable + master

**Comment by sualfred** [comment]
For reference: https://forum.kodi.tv/showthread.php?tid=340366

**Comment by ksooo** [comment]
> Add a label to myvideonav.xml in Estuary: $INFO[ListItemAbsolute(0).Label]

Please post a diff, then I don't need to guess/figure where eactly to put this.

**Comment by sualfred** [comment]
> > Add a label to myvideonav.xml in Estuary: $INFO[ListItemAbsolute(0).Label]
> 
> Please post a diff, then I don't need to guess/figure where **exactly** to put this.

Just put it in the end of myvideonav so it won't be overlapped by other elements.

Or create a custom dialog as temporary global available overlay:

Custom_1146_test.xml

`<?xml version="1.0" encoding="UTF-8"?>
<window id="1146" type="dialog">
	<zorder>999</zorder>
	<visible>!Window.IsVisible(startup)</visible>
	<controls>
		<control type="label">
			<height>50</height>
			<width>auto</width>
			<textcolor>yellow</textcolor>
			<shadowcolor>FF000000</shadowcolor>
			<label>$INFO[ListItemAbsolute(0).Label]</label>
		</control>
	</controls>
</window>`

**Comment by ksooo** [comment]
Please post a diff for myvideonav! I'm not a skinner and all this custom tralala tells me nothing.  ;-)

**Comment by sualfred** [comment]
:-)
Just place this file to your Estuary xml folder and perform a ReloadSkin() or restart Kodi:
https://we.tl/t-jKv21Jvr3Y

The funny thing is, that ListItemAbsolute(1).[infolabel] is working at home, but here in the office it returns nothing.

**Comment by ksooo** [comment]
Thanks. 

For me, only the first line ever outputs something non-empty and yes, the output is always the label of the focused item, thus I now can reproduce and debug the problem.

Where in Estuary should I see the 3rd and 4rth line outputting something non-empty?

**Comment by sualfred** [comment]
That's the strange thing. It should return something. But for some reason it won't show anything because of the dialog overlay. As soon as it's placed in myvideonav.xml you'll get other values. The values aren't passed between screens, but they should. 

Please also add these modified myvideonav.xml. It will show you the same output but on the right side of the screen and only in myvideonav.xml;
https://we.tl/t-IwQRZEaWz0

Example screen:
https://i.ibb.co/fp6ZHj1/4267-F691-D9-A2-4-C15-8957-C33-EB0-CC29-C0-png.jpg

**Comment by HitcherUK** [comment]
> The values aren't passed between the active window and the dialog, but they should.

Didn't think this ever worked to be honest.

**Comment by ksooo** [comment]
@sualfred I think I fixed it, but to be sure about this and to prevent regressions, woul you mind trying a test build? If yes, which platform?

**Comment by ksooo** [comment]
Before:
![screenshot000](https://user-images.githubusercontent.com/3226626/52356512-a49e1400-2a34-11e9-829c-268172eb3354.png)

After:
![screenshot001](https://user-images.githubusercontent.com/3226626/52356521-ac5db880-2a34-11e9-8a63-e8e81f0ddaa0.png)

**Comment by sualfred** [comment]
Yes, Windows please.

**Comment by ksooo** [comment]
https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20190206-f0f432b0-guiinfo-fix-listitemabsolute-x64.exe

**Comment by sualfred** [comment]
Tested and can confirm hat ListItemAbsolute is working now.

But during my tests I also noticed that ListItemPosition(offset) is messed up:
- No matter if negative/neutral/positive offset, the values are wrong (see screenshot)
- The output of all 3 options is completely different with added Container. prefix, but still wrong.

From the wiki:
> Shows the infolabel for an item in a Container. the item id is the position in the container relative to the cursor position.

See screenshot:
https://i.ibb.co/Cv4XmMS/9-EA84-E48-F74-D-462-D-A942-8-FBAFE2-A5701-png.jpg

New modified myvideonav.xml to represent ListItemPosition:
https://we.tl/t-kBlCYQrHMK

**Comment by ksooo** [comment]
Thanks for the update. I will take a look at the ListItemPosition problem.

**Comment by ksooo** [comment]
ListItemPosition(0) shall return the currently selected item? -1, the predeccessor of the selected item? 1 the successor of the selected item? Right?

**Comment by ksooo** [comment]
Are you sure that ListItemPosition did work in Kodi 17 or before the Kodi 18 guiinfo manager refactoring? At the first glance, this seems to be unrelated.

**Comment by ksooo** [comment]
Okay, I found something which makes the out for same offsets at least consistent for Container.ListItemPosition(x) and ListItemPosition(x).

Found a code comment that explains how it is supposed to work "// use offset from the first item displayed, taking into account scrolling" and I think it now does what it is supposed to do?

Do you think the output on the following screenshot is correct? I think so.

-1 => predecessor of first visible item (obviously not visible by I know it is Abenteuer)
0 => first item that is visible => Action
1 => second visible item => Animation
<img width="287" alt="screenshot 2018-11-03 at 09 29 12" src="https://user-images.githubusercontent.com/3226626/52372869-8991cb00-2a59-11e9-868a-f545c17c88a8.png">

**Comment by sualfred** [comment]
Yep, that looks correct to me.

**Comment by ksooo** [comment]
@sualfred could you give this new test build a try. It should fix both issues you've reported here: http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20190206-b62220b7-guiinfo-fix-listitemabsolute-x64.exe

**Comment by sualfred** [comment]
Tested, but ListItemPosition is still wrong - or lets say party wrong now :). The labels are +1 ahead.

See:
https://i.ibb.co/pZx6MC0/BCF597-F9-3-F39-47-A4-A400-568-BB6-ECDEBA-png.jpg

It should be:
ListItemPosition(-1): ...
ListItemPosition(0): Action
ListItemPosition(1): Animation

**Comment by sualfred** [comment]
Wait a second, too fast. I guess the list container is displayed a little bit offset to get a smooth transition. I'll double check it.

**Comment by ksooo** [comment]
What I see on your screen shot looks correct to me, given that I got the 'listitemposition' feature right.

**Comment by sualfred** [comment]
Yeah, my fault. The view I've tested has another movement defintion which makes the postion 1 look like position 0. 

Sorry for the noise, everything is fine.

**Comment by ksooo** [comment]
Okay, thanks for testing. I will PR the fix, then.

**Comment by sualfred** [comment]
Np, thanks for the super fast fixing.

**Comment by ksooo** [comment]
Yeah, I just was in the right mood today, I guess. I may behave completely like an asshole the other day. ;-)
