### ISSUE TITLE
Smart Playlist [Video] when using Emby sources fails

### ISSUE THREAD

**Issue by zalaare** [xbmc/xbmc#15453]
### Describe the bug

I noticed @ LibreELEC v8.95.003 my Smart Playlists stopped working:
- Using the Kodi context menu directly on a playlist and choosing "Play" would lockup kodi for 10s or so then silently do nothing. [NOT PLAY]
- Browsing into the same playlist would properly show the video files queued in the playlist.  Selecting one at random and using the Kodi context menu directly on that video choosing "Play from here" would play the video, but fail to play the following.

## Expected Behavior

Obviously, this shouldn't happen.  The playlist should play as expected.

## Possible Fix

I narrowed the problem to a specific commit:
  https://github.com/xbmc/xbmc/commit/4621220312a0fa04cdc5e36e5a0718208908da79
I've patched the commit out of LibreELEC 9.0 final release and my playlists work properly again.
I do /not/ have the knowledge to explain why this commit breaks these playlists.

### To Reproduce

1.  Create Smart video Playlist using video sources hosted from an Emby Server.  EXAMPLE:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<smartplaylist type="episodes">
    <name>Friends</name>
    <match>all</match>
    <rule field="tvshow" operator="is">
        <value>Friends</value>
    </rule>
    <order direction="ascending">random</order>
</smartplaylist>
```
2. Using context menu choose Play on your playlist
3.  NOT Profit

### Debuglog

The /failing/ debuglog can be found here: [kodi-8.95.003-smart_playlist-debug.log](https://zalaare.freeddns.org/logs/kodi-8.95.003-smart_playlist-debug.log)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 8.95.003/9.0.0
 - Kodi version: 18.0rc5.2-Leia 18.0-Leia

**Comment by MartijnKaijser** [comment]
@enen92 any idea maybe?

**Comment by enen92** [comment]
@zalaare what add-on (or how) are you populating the library with emby tvshows? The steps to reproduce need a bit more detail since I don't use emby.

**Comment by zalaare** [comment]
Addon I am using and instructions how how to populate kodi database with it.
https://kodi.wiki/view/Add-on:Emby_for_Kodi

**Comment by enen92** [comment]
@zalaare I spent some time trying to replicate the setup and initially I could reproduce the error. Unfortunately at some point while debugging the items in the library were no longer playing so I decided to update the addon to the beta version in order to check if it was a known issue. The playback issue was solved and...I could no longer reproduce your reported issue. Both play in the smartplaylist context menu and "play from here" works as expected. This leads me to think the issue was in the addon itself and not in kodi. Are you running the beta version of the addon by any chance?

@angelblue05 do you know of any change introduced in your addon (beta version) that could help explaining the difference between the beta and stable versions in what concerns this issue? Can you reproduce this issue/ Is there anything to fix in kodi at all?

**Comment by angelblue05** [comment]
@zalaare 
Why are you posting here? That is not how to report an issue at all. I had no idea of your post, until just now.

Please follow this here and open a proper post on the emby for kodi forums or github. Thank you.
https://github.com/MediaBrowser/plugin.video.emby/wiki/how-to-report-an-issue

**Comment by enen92** [comment]
@angelblue05 I'll close this as it looks unrelated to Kodi/invalid. Ping me / open an issue if you find anything that needs to be fixed.

**Comment by zalaare** [comment]
I'm using the beta plugin (v4.0.12a) and still continue to see issues (Using LE 9.0.1).

@enen92 did you test using Kodi master or Leia 18.1?

@angelblue05 Since this a problem introduced when Kodi made a change (see above) and effected Kodi playlist functionality (NOT Emby), I (apparently) wrongly assumed this was an unforeseen consequence in Kodi, where I then reported the issue.

**Comment by angelblue05** [comment]
There has been some changes in the playback area with the add-on during that time as well. With Leia, we moved away from having plugin paths in the database and moved to strm links which is still experimental. Please do a proper post like I asked previously, so I can have a look at your issue. If it is to do with Kodi after all, I will let enen92 know and get your issue reopened here. Thank you.
