### ISSUE TITLE
Minix NEO U9-H Kodi 18 Lea - loosing synchronity on playback

### ISSUE THREAD

**Issue by 123kajote** [xbmc/xbmc#15552]
### Describe the bug
Here is a clear and concise description of what the problem is:

On playback Kodi 18 Leia periodicaly looses "normal" playback - video speed becomes someway faster, sound is not sinchro, subtitles are not longer visible. It helps when I push back buton - it rools few seconds back, the it's all good... 
but after some time (5-10 minuts) - it repeats all over again...

I have tested many different videos, its every playback problem.

Kodi 17.6 Krypton didnt hade those problems.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Is there a option in Kodi that it must be checked or something?

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android - Minix NEO U9-H android box
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18 Leia

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
We will need a debuglog for that and you missed to provide it. Please submit that debuglog. 

I'll mark this issue as invalid for the time being. The label will be removed after you added the missing log.

**Comment by 123kajote** [comment]
i have no idea have to get a debuglog from standalone android box?
I am not so much experienced...

Propably is the best when I go back to Krypton...

**Comment by DaVukovic** [comment]
Follow this how-to to provide the log. 

https://kodi.wiki/view/Log_file/Easy

**Comment by 123kajote** [comment]
i uploaded it through kodi

https://paste.kodi.tv/gonecatudo

**Comment by 123kajote** [comment]
i think it happens arround 13 minute... and I pushed back button - then it corrected - arround 17 minut

**Comment by 123kajote** [comment]
also there is a funy glitch... when i go select movie/states/france (or any state)... i get for every movie 2,3 even 4 times the same movie listed in the list 
http://shrani.si/f/2b/BD/4SVXEl7B/img20190221081104.jpg

this Leia version.. is not yet fully tested, is it

is there a Way to roll back update to Krypton?

**Comment by lexius** [comment]
I have the same issue

**Comment by 123kajote** [comment]
> 
> 
> I have the same issue

tough luck..
nobodi cares..

I roll over to Kodi Krypton.. and disabled updates.. it works for me...

**Comment by fablarosa** [comment]
Same issue here, but it looks like nobody cares because the bug is still in a unassigned state.  
I'll have to revert back to 17.6.
