### ISSUE TITLE
Kodi 18.3 (win10) crashes during TV (thetvdb) update scan

### ISSUE THREAD

**Issue by at2010** [xbmc/xbmc#16432]
### Describe the bug
Here is a clear and concise description of what the problem is:

System: Windows 10 1809 x64, Kodi 18.3. Skin=Confluence. TheTVDB scraper version=3.0.15
Every time I use the manual Library Update, it is now crashing while scanning using The TVDB scraper. 
A Stacktrace file is created but is empty. 
No crashlog file is produced.
System debug logging is enabled.

The last TV series noted in the log was recently moved to a different hard drive so the scraper is probably trying to read the local information first.
Local series information was created prior to the move using the System/Media/Library Export Video Library /separate + thumbnails + fanart + actor thumbs
A Clean Library operation was performed before the Update operation
I installed the Kodi Log uploader but it does not allow one to choose a saved log.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The update should complete without errors

## Actual Behavior

Several different errors appear in the kodi.log file including SQLITE insert errors and FFMPEG warnings/errors. 
The log terminates abruptly after several calls to function LoadArt

## Possible Fix

The SQLite insert should be fixed to insert a valid Float value for column fVideoAspect in table streamdetails

### To Reproduce
1. Open Kodi 18.3
2. Add or update TheTVDB TV meta information scraper
3. Add or use existing series source using TheTVDB as a scraper
4. Export Video library separate+ fanart + actor thumbs and exit Kodi
5. Move series folder to new location still within the monitored sources folders.
6. Start Kodi
4. Clean Video Library
5. (manual) Update Video Library

### Debuglog

The debuglog can be found here:
https://paste.ubuntu.com/p/xfHdYDPT2Z/

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 Home 1809 x64
 - Kodi version: 18.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by yitzhaq** [comment]
I am seeing the same symptoms described, started today without any active changes on my part, so likely a plugin update. 18.3 running on Ubuntu Disco x86_64 with PPA package 2:18.3+git20190621.1610-final-0disco.

**Comment by HitcherUK** [comment]
We are aware and it’s caused by changes to the tvdb. See forum for temporary workaround.

**Comment by at2010** [comment]
Ahhh... Thank you. I see from this post that there are several issues pending:
[The TVDB forum](https://forums.thetvdb.com/viewtopic.php?p=155289#p155289)

They seem to like messing things up... alot ;-)

**Comment by cjthompson** [comment]
That forum link is not valid. Does someone have a link or explanation of the workaround?

**Comment by at2010** [comment]
I did not have to remove the TVDB plugin files. 
Here is another way to fix the auto update at startup/can't start Kodi with TheTVDB problem:
1. Find the file guisettings.xml in folder Kodi\userdata (in windows this is in %appdata%\Kodi\userdata)
2. Edit guisettings.xml change the line
   `<setting id="videolibrary.updateonstartup" default="true">true</setting>`
to
   `<setting id="videolibrary.updateonstartup" default="true">false</setting>`
and save.
3. Start kodi
4. Edit each video source using TheTVDb as an information provider.
5. Change "Choose Information Provider" to "The Movie Database".
6. If you did not choose Yes to Rescan Library then perform a manual update.

**Comment by KarellenX** [comment]
Fixed...

https://github.com/xbmc/repo-scrapers/pull/127

https://github.com/xbmc/repo-scrapers/pull/128

**Comment by at2010** [comment]
I verified the patched plugin works, thank you @HitcherUK.

BUT...
I am very concerned that a single (still correct) character in a regular expression can cause Kodi to panic and quit. I don't know where to to look in the code but I would guess this is caused by an unhandled exception as the result of an empty regex.

AND...
I am still seeing these errors in the log file:
```
ERROR: SQL: [MyVideos116.db] SQLite error SQLITE_ERROR (no such column: Inf)
                                            Query: INSERT INTO streamdetails (idFile, iStreamType, strVideoCodec, fVideoAspect, iVideoWidth, iVideoHeight, iVideoDuration, strStereoMode, strVideoLanguage) VALUES (27580,0,'hevc',Inf,1920,800,7791,'','eng') (no such column: Inf)
```
This is a true bug if a float is not inserted into fVideoAspect in the streamdetails table. Whatever value Inf is supposed to be should be set to a default 0.0 value. There should be no reason it is not a valid aspect ratio since any supported video file will parse a Height and Width in pixels.

**Comment by DaVukovic** [comment]
>I am still seeing these errors in the log file:

unrelated to this bug

And (and maybe I'm wrong, because I'm not a dev) I don't see a reason why `Inf` should be added to a field where Kodi would expect a float instead of a char. If you compare the value to the fields where they should be added:

idFile, iStreamType, strVideoCodec, fVideoAspect, iVideoWidth, iVideoHeight, iVideoDuration, strStereoMode, strVideoLanguage

27580,0,'hevc',Inf,1920,800,7791,'','eng'

So Kodi tries to add: 

27580 -> idFile (expects an integer, hence the "i" at the beginning - correct value given )
0 -> iStreamType (expects an integer, hence the "i" at the beginning- correct value given )
hevc -> strVideoCodec (expects a string, hence the "str" at the beginning - correct value given )
Inf -> fVideoAspect (expects a float, hence the "f" at the beginning - **incorrect value given** )
1920 -> iVideoWidth (expects an integer, hence the "i" at the beginning - correct value given )
800 -> iVideoHeight (expects an integer, hence the "i" at the beginning - correct value given )
7791 -> iVideoDuration (expects an integer, hence the "i" at the beginning - correct value given )
'' -> strStereoMode (expects a string, hence the "str" at the beginning - no (but still correct) value was given )
eng -> strVideoLanguage (expects a string, hence the "str" at the beginngin - correct value given)

So I would more check if there's a char at your streamdetails where there should be a float or, if `Inf` is meant as "Infinite", then there's probably a bug somewhere where Kodi probably devides through `0`. 

In any way, it's all not related to this bug and you should open a new one.
