### ISSUE TITLE
Dolby Vision content displays incorrectly after Display Refresh Rate adjustment

### ISSUE THREAD

**Issue by quietvoid** [xbmc/xbmc#17451]
### Describe the bug
Here is a clear and concise description of what the problem is:

There is a bug that causes Dolby Vision streams to not be reflagged as Dolby Vision after Kodi adjusts the display's refresh rate. The bug causes the display to switch back to the default SDR mode.
This does not happen with HDR10 content, so it is specific to Dolby Vision.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

After Kodi's refresh rate adjustment, the display should be back in Dolby Vision mode.

## Actual Behavior

The display mode switches to SDR, which displays Dolby Vision content incorrectly.

## Possible Fix

I assume this happens because Kodi does not send a signal that the content is Dolby Vision after the refresh rate change.

### To Reproduce

1.  Enable automatic display refresh rate adjustment in Player settings.
2. Play a Dolby Vision title in Kodi Netflix add-on (https://github.com/CastagnaIT/plugin.video.netflix)
3. Display switches to Dolby Vision mode, the video starts and looks fine.
4. Kodi adjusts the display refresh rate, and when the video displays again it is in SDR mode.
5. The display does not show Dolby Vision mode.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/ayukihapan.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

There is an opened issue in the Netflix add-on repository: https://github.com/CastagnaIT/plugin.video.netflix/issues/505
Related: https://github.com/xbmc/xbmc/pull/16929#issuecomment-596649862

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

The device is a FireTV Stick 4K, where Kodi 18.6 is installed with Netflix add-on version 1.0.0.
Furthermore, the device supports forcing Dolby Vision mode in all applications.
Enabling Dolby Vision at the global settings level, this issue does not happen and the expected outcome is correct.

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android, FireTV
 - Kodi version: 18.6, armv7a

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by CastagnaIT** [comment]
After investigating a similar problem with other developers, we were able to understand a little more about this problem

Discussion in to PR https://github.com/peak3d/inputstream.adaptive/pull/440

When a manifest (handled by InputStream Adaptive) of the video to be played have a wrong or unspecified framerate to the video representation, cause a wrong Kodi framerate switch with loss of dolby vision signal and messy colors.

so when the framerate value is missing, Kodi must independently identify the proper framerate, but seem that something is not being done correctly.

Currently with NF i have found the problem in the manifest and fixed the wrong refresh rate property value, now DV seem working correctly (tested only on Kodi 18)

there is a need for more in-depth analysis

**Comment by quietvoid** [comment]
That's good news! I will follow the progress in the comments.

Do you still believe this issue is still relevant to the Kodi team? I'm not sure if it should stay open if the issue is external.

**Comment by CastagnaIT** [comment]
the issue caused by the framerate switch after a missing/wrong framerate value is still unclear
the framerate switch is managed by Kodi core
then the issue need more in depth analysis to kodi

**Comment by matthuisman** [comment]
i have another user with a Nvidia shield and it does not happen for them.

We may need a another way to test for it better.
I'll see if I can create a test strm file and leave out framerate so the issue arises reliably.

**Comment by quietvoid** [comment]
Hi @CastagnaIT, @matthuisman. I have just tested the test version for the Netflix addon posted here: https://github.com/peak3d/inputstream.adaptive/pull/440#issuecomment-629608100

On the FireTV Stick 4K, I enabled Kodi refresh rate switching to Always with 0.5s delay.
I played multiple titles and the Netflix stream info shows 23.976 fps, the TV plays seamlessly without a noticeable refresh rate change. Dolby Vision still looks good.

Before playback, the debug OSD shows 60 fps. When the Dolby Vision playback starts, the FPS is capped to 23.4-24.4 fps.

So I would say the issue is fixed even on the FireTV Stick 4K. :smile:

**Comment by matthuisman** [comment]
The issue is still there, it's just not showing up if the framerate changes before playback starts.

@quietvoid 
Can you try this file and see if the problem occurs?
**http://f.mjh.nz/hls_dolby_vison_no_framerate.strm**
It's a .strm file - just download it somewhere Kodi can access it and then click on it via Kodi filemanager.

**Comment by quietvoid** [comment]
@matthuisman I have loaded this file on Kodi but it only plays as audio. There's no change to a Dolby Vision mode.

**Comment by matthuisman** [comment]
Oh. I know. Your ia version won't support Dolby vision in HLS yet. I'll try find a mpd example to use instead

**Comment by matthuisman** [comment]
@quietvoid 
try this:
http://f.mjh.nz/mp4_dolby_vision_hd.strm

Its only 1920x1080 but should hopefully make the problem happen.
It's FPS is 59.94 - so make sure kodi set to something other than that.

**Comment by quietvoid** [comment]
@matthuisman The mp4 .strm file stays a long a time at `Please wait...`, then displays garbage video after caching.
Kodi reports the display has changed refresh rate (60 FPS) but Dolby Vision is not triggered.

**Comment by matthuisman** [comment]
@quietvoid 
Could you try this and confirm it plays fine
http://f.mjh.nz/mpd_dolby_vision.strm

**Comment by quietvoid** [comment]
@matthuisman The first one does not play, it just changes the refresh rate, shows a black screen and closes shortly after.

The no_framerate file doesn't start at all, just shows the spinner for a fraction of a second and nothing else.

**Comment by matthuisman** [comment]
ahh bummer.
I tried to convert the HLS to MPD but obviously didn't work.

I can't find any MPD Dolby Vision test files online.
Except for 8.1 profile one - but that has a fallback to HDR10 so may be hard to tell if it isn't aactually working.

Would be great if you could install the latest Leia IA version which allows for HLS Dolby Digital?

Here it is:
https://jenkins.kodi.tv/job/peak3d/job/inputstream.adaptive/job/Leia/38/artifact/cmake/addons/build/zips/inputstream.adaptive+android-armv7/inputstream.adaptive-2.4.4.zip

To install on Android you need to do
1) install downloaded zip
2) restart kodi
3) uninstall inputstream adaptive
4) restart kodi
5) install downloaded zip
6) restart kodi

Once that's installed, you should be able to playback this fine:
http://f.mjh.nz/hls_dolby_vision.strm

and this should cause the colour issue:
http://f.mjh.nz/hls_dolby_vision_no_framerate.strm

**Comment by quietvoid** [comment]
I have tried both 8.1 files, they both work and do fallback to HDR10.

Installed IA 2.4.4 and followed the instructions. Both files get stuck to `Please wait...` after refresh rate change and continue playing in the background.

**Comment by matthuisman** [comment]
before the refresh they are OK though and show as DV?
eg. You can change refresh delay to 6 seconds to make it easier to check

**Comment by quietvoid** [comment]
No, they don't change the display mode/trigger Dolby Vision. It is still SDR.

**Comment by matthuisman** [comment]
@quietvoid 
I was reading kodinerds and it appears the pause on noisey audio may be causing this issue.

Are you able to try this Android kodi build:
https://jenkins.kodi.tv/job/Android-ARM/18067/artifact/kodi-20200514-ee2959ce-PR17868-merge-armeabi-v7a.apk

That is Leia nightly with the pause audio commit removed

**Comment by quietvoid** [comment]
Tested this again on 1fe9e9e43c30932f26fc25a43df50511cab30aa4 with strm files in this:
[p8.1-streams.zip](https://github.com/xbmc/xbmc/files/7533848/p8.1-streams.zip)

The MPD one works as expected, but the HLS plays in the background of the GUI.
Both trigger Dolby Vision.

Tried playing the HLS strm with Kodi 19.3 and the video plays in the background as well, so that's not new.
MPD strm file doesn't play at all in 19.3.

I'll close this as the core issue of Dolby Vision is fixed.
