### ISSUE TITLE
ISO files don't show up on directory

### ISSUE THREAD

**Issue by onesolo** [xbmc/xbmc#18897]
### Describe the bug
Here is a clear and concise description of what the problem is:

On my Shield TV (2015) using Kodi 19 beta, it also happened on Kodi 18, I can't see my ISO files, whether I put them on a USB or on a network path (over my NAS). 
This happens on Kodi 18.x and also on latest Kodi 19.x betas.
If I use Kodi on Windows this doesn't happen, ie it shows ISO files just fine over directories.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
To be able to show ISO files on the directories inside Kodi.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version 18 and 19 beta:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by HeresJonny** [comment]
In my case the ISO files show up in Windows 18.9 but not in CoreELEC 9.2.5 (same branch).

**Comment by HeresJonny** [comment]
Also no ISO files on Matrix latest windows nighlies from december.

**Comment by HeresJonny** [comment]
Some more info: If the Archive Support add-on by Spiff is removed, the .iso files become visible. However, after they are added to the library (music videos) in my case, any attempt to play the item ends in an error like so:

2020-12-05 22:42:35.522 T:2004     INFO <general>: VideoPlayer::OpenFile: smb://192.168.1.185/TV-Movie/_Blu-ray/Gentle Giant - Octopus (1972 RM2015 BR)/OCTOPUS.ISO
2020-12-05 22:42:35.523 T:2672     INFO <general>: Creating InputStream
2020-12-05 22:42:35.529 T:2672    ERROR <general>: XFILE::CFileCache::Open - failed to open source <smb://192.168.1.185/TV-Movie/_Blu-ray/Gentle Giant - Octopus (1972 RM2015 BR)/>
2020-12-05 22:42:35.529 T:2672    ERROR <general>: CVideoPlayer::OpenInputStream - error opening [smb://192.168.1.185/TV-Movie/_Blu-ray/Gentle Giant - Octopus (1972 RM2015 BR)/OCTOPUS.ISO]
2020-12-05 22:42:35.529 T:2672     INFO <general>: CVideoPlayer::OnExit()
2020-12-05 22:42:35.857 T:2004     INFO <general>: CVideoPlayer::CloseFile()
2020-12-05 22:42:35.857 T:2004     INFO <general>: VideoPlayer: waiting for threads to exit
2020-12-05 22:42:35.857 T:2004     INFO <general>: VideoPlayer: finished waiting

**Comment by onesolo** [comment]
> 
> 
> Some more info: If the Archive Support add-on by Spiff is removed, the .iso files become visible. However, after they are added to the library (music videos) in my case, any attempt to play the item ends in an error like so:
> 
> 2020-12-05 22:42:35.522 T:2004 INFO : VideoPlayer::OpenFile: smb://192.168.1.185/TV-Movie/_Blu-ray/Gentle Giant - Octopus (1972 RM2015 BR)/OCTOPUS.ISO
> 2020-12-05 22:42:35.523 T:2672 INFO : Creating InputStream
> 2020-12-05 22:42:35.529 T:2672 ERROR : XFILE::CFileCache::Open - failed to open source <smb://192.168.1.185/TV-Movie/_Blu-ray/Gentle Giant - Octopus (1972 RM2015 BR)/>
> 2020-12-05 22:42:35.529 T:2672 ERROR : CVideoPlayer::OpenInputStream - error opening [smb://192.168.1.185/TV-Movie/_Blu-ray/Gentle Giant - Octopus (1972 RM2015 BR)/OCTOPUS.ISO]
> 2020-12-05 22:42:35.529 T:2672 INFO : CVideoPlayer::OnExit()
> 2020-12-05 22:42:35.857 T:2004 INFO : CVideoPlayer::CloseFile()
> 2020-12-05 22:42:35.857 T:2004 INFO : VideoPlayer: waiting for threads to exit
> 2020-12-05 22:42:35.857 T:2004 INFO : VideoPlayer: finished waiting


Just installed 19 beta 2 on Windows and no longer shows ISO files. After  disable Archive Support addon, the files are showed again.

**Comment by onesolo** [comment]
Tried on my Shield TV but disabling Archive Support addon doesn't do anything, ie. ISO files are not showed.

**Comment by enen92** [comment]
Can't reproduce this on my android devices.

**Comment by onesolo** [comment]
> 
> 
> Can't reproduce this on my android devices.

Do you mean by that? That it shows ISO files? Do you have the Archive Support addon installed?

**Comment by enen92** [comment]
I tested this on my android TV devices using one of the latest nightlies, by copying some iso files to a usb drive and pluging it to the device. The drive was automounted by the OS and the isos are visible (and playable) in Kodi. Not using archive support add-on as far as I can tell, just vanilla Kodi.

**Comment by HeresJonny** [comment]
No idea about Android, my problem is with Windows and CoreElec and playing ISO over SMB/SAMBA.

**Comment by ace20022** [comment]
I have troubles with isos and the beta 2 that are related quite likely. The vob files inside the isos get scanned to library. They all have ```archive://../../*.vob``` as a prefix.

**Comment by roldob** [comment]
I have similar problem with Kodi 19 Beta2 and nightlies...
The TMDB scraper cannot find new iso files and cannot see them in library. 
It can play the existing iso by right clicking on title and click on play..., but the fast rewind/forwind does not work too.

**Comment by HeresJonny** [comment]
To distinguish (currently on Matrix nightly 2021-01-12): 
ISO files from DVD rips seem to show up. They can then be opened in media view but only .VOB files play, .ifo files cause an error. That might also explain why the .ISO is not directly playable.
ISO files from Bluray rips don't show up at all and are not playable.

In Windows, I use Total Commander with a plug-in that is able to open ISOs. When opening Bluray ISOs they also appear empty although the file plays fine with VLC.

There might be a problem with the current parser.

**Comment by dabl2** [comment]
> I have troubles with isos and the beta 2 that are related quite likely. The vob files inside the isos get scanned to library. They all have `archive://../../*.vob` as a prefix.

I am seeing something similar with the RC on Nvidia Shield TV.  I have many Blu-Ray and UHD .ISO images and now when updating the library, files inside these .iso images such as CERTIFICATE\id.bdmv are getting matched to titles at the themoviedb.org and added to library as bogus titles such as Kung Fu Hustle and The Certificate etc and multiple entries for each are created. These have 'udf://../../ as a prefix. If I simply clean the library just after, these all get cleared out of the library.

Further, Blu-Ray movie .iso images that do not have an entry at themoviedb.org for which I've created .NFO files are now not getting scanned into the library.  This is new behavior that may have started with earlier builds but I had not tried updating the library with those so am just seeing it now.

**Comment by dabl2** [comment]
> I have similar problem with Kodi 19 Beta2 and nightlies on Windows 10...
> The TMDB scraper cannot find new iso files and cannot see them in library.
> It can play the existing iso by right clicking on title and click on play..., but the fast rewind/forwind does not work too.

I see exactly the same thing with the RC on Android running on an Nvidia Shield TV

**Comment by blanchoid** [comment]
I have exactly the same problem, I am using Kodi 19.0, the Blu Ray ISOs as far as I know were there and then they weren't is seems to have removed them after doing a Library update.

The Version 19.0 is pretty much plain vanilla with the Amber skin, no addons (did not want to complicate things).

I have removed and reinstalled this and got the ISOs to display again, but then after a while they have gone again, the odd thing is that the DVD ISOs I have also now open up into VIDEO_TS folder within the DVD instead of playing!

If I right click and select Play I get the following:
![image](https://user-images.githubusercontent.com/56632127/110149301-c6b21e00-7dd5-11eb-831a-29b0cf740370.png)

This is only happening on one of my Kodi machines, the other one attached to the telly is fine, both are Windows 7 machines and are attached to a MariaDB on my NAS so I can restart a file where I left off.

The i7 machine that is having the problem seems to want to rescan everything again as the dot does not appear to say whether or not the file has been played or not, right click doesn't give any Information either, only the option to scan to Library as if it is a new file! Like this:
![image](https://user-images.githubusercontent.com/56632127/110149478-ff51f780-7dd5-11eb-8c34-f4f351b41ee0.png)

This has only happened since I updated to 19.0

Any help would be appreciated!!

**Comment by DaVukovic** [comment]
I don't have any issue with ISO files and as long as there's no debuglog (even the message at the skin tells that where to look at) we can't help at all. 

So please, enable debug logging, restart kodi, reproduce your issue and use https://paste.kodi.tv to provide the log

**Comment by blanchoid** [comment]
> I don't have any issue with ISO files and as long as there's no debuglog (even the message at the skin tells that where to look at) we can't help at all.
> 
> So please, enable debug logging, restart kodi, reproduce your issue and use https://paste.kodi.tv to provide the log

Hi, Just reporting back, I was setting up another Kodi box right next to the faulty one,

I was comparing the settings to see what was different...

And then I discovered 'Archive Support' in Virtual; Filesystems had installed it was needed to support subtitles.

Can some one please tell me why this is not configurable??

It says that this uses libarchive library to read a variety of archive and compression formats.

Supported formats are:
7z, bz2, gz, **ISO**, tar, tar.bz2, tar.gz, tar.xz, tgz, tbz2, xz, zip

This is where the problem lies! removed the offending subtitles app (required to uninstall the archive support) and then uninstalled this rubbish plugin!

This plugin is a major pain in the rectum as it hijaaks ISO files!! I mean what sort of person would write something like this? Without warnings? So that you cannot play ISO files, most people looking for Kodi would have their own ripped DVD/Blu Ray/CD disks! Rendering them completely useless!

I may have picked this up sooner if it had not just removed removed Blu Ray ISOs as I could not see how it behaved differently for DVD and Blu Ray ISOs!!

That is one app that will never be getting installed ver again on any of my Kodi machines and will be yelling this as loud as possible!!

**Comment by DaVukovic** [comment]
>And then I discovered 'Archive Support' in Virtual; Filesystems had installed it was needed to support subtitles.

As you (also) didn't provide a logfile, could you please tell me which subtitle add-on requires vfs.libarchive to be installed? I just tried the most common ones (opensubtitles.org and Addic7ed) and those don't require any archive-add-on to be installed. 

Not saying that it's ok that an archive add-on hijacks ISO files if there's no need for. Just curious which subtitle add-on requires such a dependency

**Comment by HeresJonny** [comment]
ISO playback of DVD and BluRay is fixed in one of the last nightlies. Thank you Team Kodi!

**Comment by roldob** [comment]
(Kodi 20210308 nightly, Windows 10)

Yes, it shows up in media library, but does not in simple directory (Videos/files/add videos without setting content).

(And cannot play iso by pressing enter on movie. Playback works with right-clicking on "play" only. The fast forwind/rewind still does not work on iso playback.)

**Comment by HeresJonny** [comment]
That is another bug, not corresponding to the headline here. You should open a new thread.

**Comment by roldob** [comment]
> Yes, it shows up in media library, but does not in simple directory (Videos/files/add videos without setting content).

Sorry, I have tested it again with a new iso, It does not work. It cannot find new iso and it does not shows up in movies. It can find the mkv with same name and put it into movies...
(Windows 10, 20210308 nigthly)
