### ISSUE TITLE
Bug in Kodi 20.0 Nexus

### ISSUE THREAD

**Issue by roel8032** [xbmc/xbmc#22662]
When you start a playlist .m3u file, Kodi plays it in Alphabetical order. Not in the onder of the playlist file.

On:
Android Tablet, TV box.

Bug appeared since last update.

**Comment by lrusak** [comment]
Please follow the bug report template.

**Comment by roel8032** [comment]
Developers that are not interested in a bug, are no good developers.

**Comment by ksooo** [comment]
Already fixed by https://github.com/xbmc/xbmc/pull/22609 (master) and https://github.com/xbmc/xbmc/pull/22610 (nexus).

**Comment by roel8032** [comment]
> Already fixed by #22598 (master) and #22601 (nexus). Duplicate of #22580

So we have to wait voor the next update?

**Comment by ksooo** [comment]
If you don’t rant to wait, you can use a recent Nexus nightly built.

**Comment by robross0606** [comment]
For the record, 20.1 was released today and this bug still exists.

**Comment by ksooo** [comment]
> For the record, 20.1 was released today and this bug still exists.

 Can you prove that?

**Comment by robross0606** [comment]
I stand partially corrected.  Not sure what happened really.  The first time I fired it up, things were still exactly the same kind of wrong.  But I bounced Kodi again and now it is showing "playlist" at least.  "Date" still sorts incorrectly though.  @ksooo, without getting into some type of immature p-----g contest online, what type of "proof" would you want?  A screenshot? Logs of some type?

**Comment by ksooo** [comment]
> „Date" still sorts alphabetically though.

please open a separate issue for this. 

> what type of "proof" would you want? A screenshot? Logs of some type?

haha, if you would have read and used or bug report template in the first place, you would not have to ask this question.

**Comment by robross0606** [comment]
I didn't log a new bug. Just made a single comment. Is there some unspoken trailer that _everyone_ on a forum needs to be hostile?  Take a breath, dude. Sheesh...

**Comment by ksooo** [comment]
>> please open a separate issue for this.

> everyone on a forum needs to be hostile

No idea why asking something using a kind please can be taken as being hostile.

If you find a bug and want to bring it to our attention, please file an issue. This is how we (and many many other projects) organise our work.

**Comment by robross0606** [comment]
> No idea why asking something using a kind please can be taken as being hostile.

Where did you use a "kind please"?  What started this was "Can you prove that?" which is hostile and passive-aggressive at the same time.

> If you find a bug and want to bring it to our attention, please file an issue. 

There are many _many_ instances of people reporting bugs that end up being duplicates.  Then they get flamed for creating a duplicate in the responses with things similar to your "if you would have read and used or bug report template in the first place, you would not have to ask this question.".  That's also hostile in tone.

All I did here was comment on an existing ticket.   If I could, I would simply remove all these comments and go about my day.

**Comment by ksooo** [comment]
Okay, @robross0606 I feel like investing my time for something else. It seems we're talking different languages. Cheers.
