### ISSUE TITLE
Can't edit movie details through Chorus

### ISSUE THREAD

**Issue by Hoween** [xbmc/xbmc#23653]
### Describe the bug
Editing movie details through Chorus stopped working. Error message from backend is received. Editing through standard Kodi interface in TV works fine. This bug appears in some version released this year. At least last year it works normally.

## Expected Behavior
Editing movie details should works normally, same way as tv interface.

## Actual Behavior
Editing through Chorus doesn't work. After submiting dialog, error -32602 is received and nothing changes.

### To Reproduce

1. Open Chorus, open Movie section
2. Find any movie, click on hamburger menu, then on Edit.
3. Change any details and click on Save

### Debuglog

The debuglog can be found here:
Request after clicking on Save
```
POST | http://192.168.100.4/jsonrpc?VideoLibrary.SetMovieDetails=

{
	"id": 5,
	"jsonrpc": "2.0",
	"method": "VideoLibrary.SetMovieDetails",
	"params": {
		"art": {
			"fanart": "",
			"poster": "image://video@nfs%3a%2f%2f192.168.100.3%2fvolume1%2fmovies%2fFilmy%2fV%2fVelke-nic-(2023).mkv/"
		},
		"country": [
			"Czech Republic"
		],
		"director": [],
		"fanart": "",
		"genre": [
			"Documentary"
		],
		"imdbnumber": "tt27193714",
		"movieid": 4711,
		"mpaa": "",
		"originaltitle": "Velké nic",
		"plot": "How did Czech society respond to the Covid pandemic? A new documentary , reflects on the past three years to try to come to terms with the worldwide pandemic, and see if it brought about anything positive.",
		"plotoutline": "How did Czech society respond to the Covid pandemic? A new documentary , reflects on the past three years to try to come to terms with the worldwide pandemic, and see if it brought about anything positive.",
		"rating": 8.4,
		"set": "",
		"sorttitle": "",
		"studio": [],
		"tag": [],
		"title": "Velké nic",
		"trailer": "",
		"writer": [],
		"year": 2023
	}
}

```
Response:
```
{
	"0": {
		"error": {
			"code": -32602,
			"data": {
				"method": "VideoLibrary.SetMovieDetails",
				"stack": {
					"message": "Received value does not match any of the union type definitions",
					"name": "art",
					"type": [
						"null",
						"object"
					]
				}
			},
			"message": "Invalid params."
		},
		"id": 5,
		"jsonrpc": "2.0"
	}
}
```

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0
 - Kodi version: Kodi 20.2, Chorus 19.x-2.4.8

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DaVukovic** [comment]
Hi @Hoween 

Thanks for your report. 

Unfortunately I can't reproduce your issue with Kodi 21.0-Alpha2 on Linux (Fedora 37) using Brave-Browser. 

I've tested changing the name of a movie and its plot. Both worked fine via the WebIF. 

Could you please test with a newer Kodi version (21.0-Alpha) and confirm either the issue is already fixed or not?

**Comment by Hoween** [comment]
I'm using Kodi via LibreELEC on RPi, so it's not easily possible to change the app. If it's working in next development version, I can wait for stable version and confirm or reject the solution.

**Comment by Hoween** [comment]
Hi @DaVukovic 
Today I updated to newest Libreelec with Kodi, but the problem remains.

```
Status report
    Chorus version    19.x-2.4.8
    Kodi version    21.0
```

POST | http://192.168.100.4/jsonrpc?VideoLibrary.SetMovieDetails
```
[
   {
      "jsonrpc":"2.0",
      "method":"VideoLibrary.SetMovieDetails",
      "params":{
         "movieid":4726,
         "title":"Život pro samouky",
         "plotoutline":"",
         "plot":"Know what this is about?\n    Be the first one to add a plot.",
         "studio":[
            
         ],
         "year":0,
         "mpaa":"",
         "rating":5.1,
         "imdbnumber":"tt27837981",
         "sorttitle":"",
         "originaltitle":"Život pro samouky",
         "director":[
            
         ],
         "writer":[
            
         ],
         "genre":[
            "Comedy"
         ],
         "country":[
            "Czech Republic"
         ],
         "set":"",
         "tag":[
            
         ],
         "trailer":"",
         "fanart":"",
         "art":{
            "fanart":"",
            "poster":"image://video@nfs%3a%2f%2f192.168.100.3%2fvolume1%2fmovies%2fFilmy%2fZ%2fZivot-pro-samouky-(2023).mkv/"
         }
      },
      "id":9
   }
]
```

Response:
```
[
    {
        "error": {
            "code": -32602,
            "data": {
                "method": "VideoLibrary.SetMovieDetails",
                "stack": {
                    "message": "Received value does not match any of the union type definitions",
                    "name": "art",
                    "type": [
                        "null",
                        "object"
                    ]
                }
            },
            "message": "Invalid params."
        },
        "id": 9,
        "jsonrpc": "2.0"
    }
]
```

**Comment by pixelsocialclub** [comment]
Hello @DaVukovic and @Hoween 
I have also the same issue here. Using a fresh install of latest stable LibreELEC / Kodi from today, on a Pi4b. Accessing Chorus with Firefox in case it matters.
[{"error":{"code":-32602,"data":{"method":"VideoLibrary.SetMovieDetails","stack":{"message":"Received value does not match any of the union type definitions","name":"art","type":["null","object"]}},"message":"Invalid params."},"id":6,"jsonrpc":"2.0"}]

**Comment by Hoween** [comment]
This problem still remains, even in newest stable version of Librelec / Kodi.

**Comment by neo1973** [comment]
Confirmed. The problem is caused by the empty path in the "art" object like:
```
         "art":{
            "fanart":"",
            "poster":"image://video@nfs%3a%2f%2f192.168.100.3%2fvolume1%2fmovies%2fFilmy%2fZ%2fZivot-pro-samouky-(2023).mkv/"
         }
```
Sending `null` instead of `""` or omitting `fanart`entirely  doesn't cause the problem.

**Comment by neo1973** [comment]
Closed because the error is already tracked in the Chorus2 bug tracker: https://github.com/xbmc/chorus2/issues/457
