### ISSUE TITLE
Update 21 on Android TV broke TLS ftp source, Windows works

### ISSUE THREAD

**Issue by nixx1338** [xbmc/xbmc#25118]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi 21.0 on Android TV (and Android in general) broke connectivity to FTP sources which require additional flags such as TLS, e.g. "ftp://host.com:21/files/|auth=TLS&verifypeer=false". This functionality still works on Windows. As per [support forum](https://forum.kodi.tv/showthread.php?tid=377271) multiple people face the same issue.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Remote folder is accessible and opens in file browser

## Actual Behavior

Kodi takes a few seconds to attempt connection to the remote folder, ultimately shows empty folder. No notification.

## Possible Fix

N/A

### To Reproduce

1. Add FTP sources with flags such as |auth=TLS&verifypeer=false
2. Add folder using new source
3. Attempt to open folder

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/15209595/kodi.log)
From forum user blunden:
[debug log](https://pastebin.com/YZ2J1q9t)

### Screenshots 
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

N/A

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android (Shield TV)
 - Kodi version: 21.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by gsko** [comment]
I am experiencing this bug on my Nvidia Shield using
- Kodi Build: 21.0.1
- Git: 202040409-7e760d1063
- Compiled: 2024-04-09

The Nvidia Shield is based on:
- Android TV 11.0.0
- Linux Kernel: 4.9.141-tegra-gfad87...

**Comment by t-nor** [comment]
Same issue on nvidia shield

**Comment by disturbed01** [comment]
same issue here

Android TV 12.0.0 API level  31 (linux kernel 4.9.269)
build 21.0.1
Git: 20240409-7e760d1063
compiled 2024-04-09

**Comment by brozikcz** [comment]
interestingly, FTP is accessible from the file manager in settings, but as soon as I want to get to FTP from movies section in the main menu, kodi gets stuck

**Comment by chewitt** [comment]
This is reported in the LibreELEC forums too, so the issue is not specific to Android: https://forum.libreelec.tv/thread/28779-ftps-broken-in-le12/

**Comment by disturbed01** [comment]
@chewitt do you happen to have any update regarding this? it's frustrating that a feature which worked perfectly prior to V21 is now dead in the water

**Comment by jezaldanluthar** [comment]
Any update on this? Also, does anybody know a way around this? Would downgrading to 20.5 fix this?

**Comment by nixx1338** [comment]
Downgrade to 20.5 as suggested above works. Walkthrough for Nvidia Shield (should be comparable for Google TV):

1. Enable network access to the device (or skip to step 4)
[https://nvidia.custhelp.com/app/answers/detail/a_id/4172/~/how-do-i-share-shield-tv-folders-with-a-pc](https://nvidia.custhelp.com/app/answers/detail/a_id/4172/~/how-do-i-share-shield-tv-folders-with-a-pc)
2. Download 20.5 apk (v7a for Shield)
[https://mirrors.kodi.tv/releases/android/arm/kodi-20.5-Nexus-armeabi-v7a.apk](https://mirrors.kodi.tv/releases/android/arm/kodi-20.5-Nexus-armeabi-v7a.apk)
3. Copy the apk to Downloads on your device.
4. Alternatively use any Android TV browser to download the apk.
Shortened URL: [https://tinyurl.com/kodi2057](https://tinyurl.com/kodi2057)
5. Install X-plore File Manager
[https://play.google.com/store/apps/details?id=com.lonelycatgames.Xplore](https://play.google.com/store/apps/details?id=com.lonelycatgames.Xplore)
6. User network connection or X-plore to create a backup of your Userdata folder to any other folder (e.g. Documents, Downloads). Userdata location: 
`\Android\data\org.xbmc.kodi\files\.kodi\userdata`
7. Uninstall latest Kodi
8. Use X-plore to install Kodi 20.5 from apk
9. Restore your Userdata folder (overwrite all)

**Comment by BBen1979** [comment]
I have the same issue with the latest build; [kodi-20240817-183eb85f-Omega-armeabi](https://mirrors.kodi.tv/nightlies/android/arm/Omega/kodi-20240817-183eb85f-Omega-armeabi-v7a.apk)

Seem there was a bug with the Curl package, 8.9.1 Should be fixed.

Source: https://forum.libreelec.tv/thread/28779-sftp-broken-in-le12/

Can anyone replace one of the latest Android 32bits build of V21.1 with the latest Curl that would be really appreciated.

Thanks

**Comment by gu3nter** [comment]
Great tobhear, can you please make an pull requests to fix the issue?

**Comment by gu3nter** [comment]
Thanks alot

**Comment by gu3nter** [comment]
Nightly from today 21.09.2024 (kodi 22), ist working now for ftps, many thanks.
Hopefully the next official kodi 21.2 Release will than also Work.

**Comment by MtestHuser** [comment]
Yes, but it still does not explain why an update to KODI 21 under Android causes this error! I mean, curl and libcurl are derived from the operating system, and it is not KODI that provides these two components.
For example, on my Android 10 device, the manufacturer has installed libcurl/7.64.1, and I do not experience this error.

However, I come from the LibreELEC sector and am familiar with the TLS-FTP issue with KODI 21 (LibreELEC 12.0.x). In that case, the underlying operating system has libcurl/8.6.0 installed, which is responsible for the problem. I tried a counter-test using `curl -k --ftp-ssl --user myusername:mypassword ftp://ftpserver.mine:21` on the SSH console. However, curl did not recognize the `--ftp-ssl` option there. An overlay downgrade to the next lower version, libcurl/8.5.0, restored the functionality of TLS-FTP. The terminal command works again with that version too.

So, what should Android users do with curl and libcurl between versions 8.6.0 and 8.9.0? Now I read that it works again under KODI 22, despite the libcurl version remaining the same. A programmer needs to explain to me how these confusing relationships can be understood!

**Comment by blunden** [comment]
> Yes, but it still does not explain why an update to KODI 21 under Android causes this error! I mean, curl and libcurl are derived from the operating system, and it is not KODI that provides these two components. For example, on my Android 10 device, the manufacturer has installed libcurl/7.64.1, and I do not experience this error.

That's incorrect. Kodi includes its own copy of curl/libcurl in the Android app. It **doesn't** rely on the OS bundled version of curl/libcurl. What the device manufacturers decide to include is therefore irrelevant. 🙂 

> So, what should Android users do with curl and libcurl between versions 8.6.0 and 8.9.0? Now I read that it works again under KODI 22, despite the libcurl version remaining the same. A programmer needs to explain to me how these confusing relationships can be understood!

They don't have to do anything besides update the Kodi app to a version bundling a newer curl/libcurl version. It was backported to Kodi 21 too (and included in 21.2 or 21.3 if I recall correctly).

**Comment by MtestHuser** [comment]
Interesting! I am surprised that it is done this way. But that’s how it is when one is not a programmer. There is so much one does not know. 
Just out of curiosity: How could I determine the current curl version used by Kodi?
