### ISSUE TITLE
Deadlock on PVR Delete After Watching

### ISSUE THREAD

**Issue by janbar** [xbmc/xbmc#26450]
### Describe the bug

Deadlock on PVR Delete After Watching: Confirming **quickly** to delete recording after watching, process run a deadlock.

## Expected Behavior

It should return to GUI main page.

## Actual Behavior

<img width="443" alt="Image" src="https://github.com/user-attachments/assets/3360a10d-55c8-4b50-a8f0-8d8454343e8b" />

## Possible Fix

It seems 2 concurrent threads inter-lock. I joined the spindump output, which shows that.

### To Reproduce

1.  Play recording until the end.
2.  At the end, the dialog occurs, then press YES in the second.

### Debuglog

[kodi-osx-x86_64_Spindump.txt](https://github.com/user-attachments/files/18929883/kodi-osx-x86_64_Spindump.txt)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [X] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: macOS 13.7.2 (Build 22H313)
 - Kodi version: 22.0.alpha1 (20250220-22885432ec)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by janbar** [comment]
The merged PR is #25629

**Comment by janbar** [comment]
Note: I implemented this feature in the addon pvr.mythtv until Omega. A similar issue was, and to fix it I had to postpone the dialog/action for a short time (1 sec) after SetRecordingPlayCount.

https://github.com/janbar/pvr.mythtv/blob/6d3589bd5b93f43ec39b137fa88952ce01753c32/src/pvrclient-mythtv.cpp#L1383C1-L1386C6

**Comment by ksooo** [comment]
@janbar sorry, I have no idea how to read the spindump output. Never had to deal with this so far, sorry. Can you tell which threads are part of the deadlock and why?

**Comment by janbar** [comment]
It could be a deadlock between 2 threads updating the video database: One updates the playCount, the other try to delete the row of recording. But it is a guess ... else I am afraid the lock is soft and these threads are waiting for a condition. 

**Thread 0x6c88    Thread name "JobWorker"**
...
                  1000  CLambdaJob<CVideoPlayer::OnExit()::$_9>::DoWork() + 25 (Kodi + 3861929) [0x11020ada9]
                    1000  CVideoPlayer::OnExit()::$_9::operator()() const + 39 (Kodi + 3862391) [0x11020af77]
                      1000  CApplicationPlayerCallback::OnPlayerCloseFile(CFileItem const&, CBookmark const&) + 1882 (Kodi + 11663850) [0x11097b9ea]
                        1000  CSaveFileState::DoWork(CFileItem&, CBookmark&, bool) + 2323 (Kodi + 7690467) [0x1105b18e3]
                          1000  PVR::CPVRGUIActionsRecordings::IncrementPlayCount(CFileItem const&) const + 130 (Kodi + 17119682) [0x110eaf9c2]
                            1000  PVR::CPVRGUIActionsRecordings::ProcessDeleteAfterWatch(CFileItem const&) const + 860 (Kodi + 17118700) [0x110eaf5ec]
                              1000  (anonymous namespace)::AsyncRecordingAction::Execute(CFileItem const&) + 79 (Kodi + 17114463) [0x110eae55f]
...


**Thread 0x6cbb    Thread name "waiting"**
...
                  1000  CThread::Process() + 50 (Kodi + 8297570) [0x110645c62]
                    1000  (anonymous namespace)::AsyncRecordingAction::Run() + 33 (Kodi + 17120433) [0x110eafcb1]
                      1000  (anonymous namespace)::AsyncDeleteRecording::DoRun(std::__1::shared_ptr<CFileItem> const&) + 534 (Kodi + 17122486) [0x110eb04b6]
                        1000  bool std::__1::accumulate[abi:v160006]<std::__1::__wrap_iter<std::__1::shared_ptr<CFileItem> const*>, bool, (anonymous namespace)::AsyncDeleteRecording::DoRun(std::__1::shared_ptr<CFileItem> const&)::'lambda'(bool, auto const&)>(auto, auto, bool, (anonymous namespace)::AsyncDeleteRecording::DoRun(std::__1::shared_ptr<CFileItem> const&)::'lambda'(bool, auto const&)) + 92 (Kodi + 17122732) [0x110eb05ac]
                          1000  auto (anonymous namespace)::AsyncDeleteRecording::DoRun(std::__1::shared_ptr<CFileItem> const&)::'lambda'(bool, auto const&)::operator()<std::__1::shared_ptr<CFileItem>>(bool, auto const&) const + 226 (Kodi + 17122994) [0x110eb06b2]
                            1000  PVR::CPVRRecordings::DeleteRecording(std::__1::shared_ptr<PVR::CPVRRecording> const&) + 102 (Kodi + 16673830) [0x110e42c26]
                              1000  PVR::CPVRRecording::DeleteMetadata(CVideoDatabase&) + 36 (Kodi + 16654852) [0x110e3e204]
                                1000  CVideoDatabase::EraseAllForFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) + 161 (Kodi + 5530945) [0x1103a2541]
                                  1000  dbiplus::SqliteDataset::exec(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) + 632 (Kodi + 11341000) [0x11092ccc8]
...

**Comment by ksooo** [comment]
> It could be a deadlock between 2 threads updating the video database: One updates the playCount, the other try to delete the row of recording.

Yep, Thread 0x6c88 Thread name "JobWorker", in `CSaveFileState::DoWork` starts a transaction which is still not committed when Thread 0x6cbb Thread name "waiting" runs `CVideoDatabase::EraseAllForFile`. 

@CrystalP look at the spindump txt file janbar provided, could the problem be that Thread 0x6cbb busy waits for the transaction started by the Thread 0x6c88 to end, which never happens?

**Comment by CrystalP** [comment]
@janbar wrote that this was already happening in previous Kodi versions and he had to work around it https://github.com/xbmc/xbmc/issues/26450#issuecomment-2676802665 so not sure but it's possible the recent change made it worse.

The "waiting" thread doesn't start a transaction but should actually. It can be a problem to update something about a file and simultaneously attempt to delete it... resulting in db corruption.
CPVRRecording::DeleteMetadata() should surround the call to EraseAllForFile() with a transaction.
Most statements of EraseAllForFile are unnecessary because of the delete trigger on the table files.

I don't know how sqlite handles concurrent access from multiple threads. Writing to a database usually requires locking data (granularity depends on db engine - db/table/range/row locks) and the locks usually remain until the implicit or explicit transaction ends.

It's possible the transaction at the top of SaveFileStateJob holds some write locks created by the calls before CPVRGUIActionsRecordings::IncrementPlayCount() and that the parallel EraseAllForFile() wants locks on the same tables. That transaction is much too large, you can remove it to see if that helps as a first step.

A way to dump sqlite held locks would be nice.

**Comment by ksooo** [comment]
> Most statements of EraseAllForFile are unnecessary because of the delete trigger on the table files.

Oh, did not know that. Let me check that first. If we could remove that call to `EraseAllForFile`, that would be a very good solution.

**Comment by CrystalP** [comment]
EraseAllForFile needs to remain at least for the file itself and its path. It won't make a difference locking-wise whether the deletions are done by explicit statements or by the delete trigger.
